fix: Reformuler objet mailto candidature spontanée
mission-apprentissage/labonnealternance pull request #1041
Opened 2024-02-01 10:43 UTC by guilletmarion

2024-02-01 11:01 UTC, alanlr requested changes
Pas d'accents ?

2024-02-01 11:08 UTC, guilletmarion commented
j'ai peur que ça cause des pb d'encoding parfois.
C'est l'objet d'un email qui est envoyé à notre BAL support, donc pas très grave

2024-02-02 08:58 UTC, guilletmarion commented
🚀

2024-02-02 09:24 UTC, guilletmarion commented
Tests sur la preview ok pour moi

2024-02-02 14:36 UTC, alanlr approved these changes

2024-02-08 08:36 UTC, merged