feat: lbac 1236
mission-apprentissage/labonnealternance pull request #1118
Opened 2024-03-05 15:25 UTC by kevbarns

https://mna-matcha.atlassian.net/browse/LBAC-1236

2024-03-05 19:30 UTC, kevbarns commented
🚀

2024-03-06 08:40 UTC, remy-auricoste approved these changes

2024-03-06 08:40 UTC, remy-auricoste commented on shared/constants/lbaitem.ts
> +export const allLbaItemType: string[] = [...Object.values(LBA_ITEM_TYPE)]
```suggestion
export const allLbaItemType: string[] = Object.values(LBA_ITEM_TYPE)
```
Pas besoin de faire une copie

2024-03-06 08:40 UTC, remy-auricoste commented on ui/components/ItemDetail/ItemDetail.tsx
> +      {amongst(kind, [LBA_ITEM_TYPE.RECRUTEURS_LBA]) && !isCandidatureLba(selectedItem) && (
```suggestion
      {kind === LBA_ITEM_TYPE.RECRUTEURS_LBA && !isCandidatureLba(selectedItem) && (
```
`amongst` ne sert à rien, j'aimerais bien le supprimer du code à terme

2024-03-06 08:40 UTC, remy-auricoste commented on ui/components/ItemDetail/LbbCompany.tsx
> +    if ([LBA_ITEM_TYPE.OFFRES_EMPLOI_LBA, LBA_ITEM_TYPE.OFFRES_EMPLOI_PARTENAIRES].includes(selectedMapPopupItem?.ideaType)) {
La logique a changé ici. C'est voulu ?

2024-03-06 08:40 UTC, remy-auricoste commented on ui/components/ItemDetail/LocationDetail.tsx
> +        {amongst(kind, [LBA_ITEM_TYPE.OFFRES_EMPLOI_LBA, LBA_ITEM_TYPE.RECRUTEURS_LBA]) && (
```suggestion
        {[LBA_ITEM_TYPE.OFFRES_EMPLOI_LBA, LBA_ITEM_TYPE.RECRUTEURS_LBA].includes(kind) && (
```

2024-03-06 08:40 UTC, remy-auricoste commented on server/src/http/controllers/jobsEtFormations.controller.ts
> +      const hasSomeApiTag = allLbaItemType.some((apiTag) => itemSources.includes(apiTag))
Les tableaux n'avaient pas les mêmes valeurs avant et dans la nouvelle version, c'est les mêmes valeurs. C'est voulu ?

2024-03-06 08:53 UTC, kevbarns commented on server/src/http/controllers/jobsEtFormations.controller.ts
> +      const hasSomeApiTag = allLbaItemType.some((apiTag) => itemSources.includes(apiTag))
Pas d'impact oui 👍

2024-03-06 09:01 UTC, kevbarns commented on ui/components/ItemDetail/LbbCompany.tsx
> +    if ([LBA_ITEM_TYPE.OFFRES_EMPLOI_LBA, LBA_ITEM_TYPE.OFFRES_EMPLOI_PARTENAIRES].includes(selectedMapPopupItem?.ideaType)) {
Non effectivement j'ai oublié de revert cette partie 👍

2024-03-06 09:19 UTC, alanlr requested changes

2024-03-06 09:19 UTC, alanlr commented on ui/components/ItemDetail/ItemDetail.tsx
> +      {amongst(kind, [LBA_ITEM_TYPE.RECRUTEURS_LBA]) && <LbbCompanyDetail lbb={selectedItem} />}
amongst rendu inutile ici

2024-03-06 09:19 UTC, alanlr commented on ui/components/ItemDetail/ItemDetail.tsx
> +      {amongst(kind, [LBA_ITEM_TYPE.RECRUTEURS_LBA]) && (
amongst rendu inutile ici

2024-03-06 09:19 UTC, alanlr commented on ui/utils/mapTools.tsx
> +      ideaType: item.ideaType === LBA_ITEM_TYPE.FORMATION ? LBA_ITEM_TYPE.FORMATION : "job",
point d'alerte ici.  les markers sur la carte ont l'air d'avoir une dichotomie formation / job au lieu de détailler les différents types d'opportunité d'emplois. y a un besoin de refacto de la mécanique ici.

2024-03-06 09:19 UTC, alanlr commented on ui/utils/tools.ts
> +      // aka. LBA_ITEM_TYPE.RECRUTEURS_LBA
case LBA_ITEM_TYPE.RECRUTEURS_LBA et default unreachable ?

2024-03-06 09:57 UTC, kevbarns commented on ui/utils/mapTools.tsx
> +      ideaType: item.ideaType === LBA_ITEM_TYPE.FORMATION ? LBA_ITEM_TYPE.FORMATION : "job",
vu ensemble, ticket créé à cet effet

2024-03-06 10:19 UTC, kevbarns commented
🚀

2024-03-06 15:27 UTC, remy-auricoste requested changes

2024-03-06 15:27 UTC, remy-auricoste commented on server/src/db/migrations/20240306130616-lbac-1908-field-migration.ts
> +                if: { $eq: ["$origin", "lba"] },
```suggestion
                if: { $eq: ["$origin", "lbb"] },
```

2024-03-08 12:57 UTC, merged