Feat migration mongodb
mission-apprentissage/labonnealternance pull request #1209
Opened 2024-04-29 08:50 UTC by kevbarns

- add `mongoDBUtils.ts` with all DB methods
- prepare `main.ts` to exploit new DB connection
- add global `models.ts` exports
- update all models with a global export as IModelDescriptor interface
- update `common.ts` with collection names

2024-04-29 09:06 UTC, remy-auricoste approved these changes

2024-04-29 09:34 UTC, moroine requested changes

2024-04-29 09:34 UTC, moroine commented on server/src/common/utils/mongodbUtils.ts
> +}
prend la version de l'API qui gère mieux les conflicts avec les collations options https://github.com/mission-apprentissage/api-apprentissage/blob/8f82002d41428aed755a8ade149b6934c6e77ea3/server/src/services/mongodb/mongodbService.ts#L169-L224

2024-05-10 06:43 UTC, moroine requested changes

2024-05-10 06:43 UTC, moroine commented on server/tests/integration/common/model.test.ts
> +  it.skip(
Il ne faut pas skip, ce bug est révélateur d'un réel probleme. Le package `zod-mongodb-schema` n'est pas compatible avec `bson@1` qui est utilisé ici... Mais uniquement `bson@5+`.

Fyi la table de compat `mongodb` <--> `bson` https://github.com/mongodb/js-bson?tab=readme-ov-file#mongodb-nodejs-driver-version-compatibility

2024-05-28 11:40 UTC, kevbarns commented on server/tests/integration/common/model.test.ts
> +  it.skip(
@moroine le soucis c'est que je ne mets pas à jour mongodb dans cette PR, je le fais dans celle-ci : https://github.com/mission-apprentissage/labonnealternance/pull/1221 donc je réactiverai le test à ce moment là.

2024-05-28 12:41 UTC, kevbarns commented on server/tests/integration/common/model.test.ts
> +  it.skip(
vu ensemble, je clôture le commentaire

2024-05-28 12:49 UTC, kevbarns commented
🚀

2024-05-29 08:32 UTC, moroine approved these changes

2024-06-06 07:06 UTC, closed without merging