Feat lbac 2066 update application api
mission-apprentissage/labonnealternance pull request #1216
Opened 2024-05-02 16:48 UTC by kevbarns

https://mna-matcha.atlassian.net/browse/LBA-2066

2024-05-20 10:52 UTC, kevbarns commented
🚀

2024-05-21 06:26 UTC, kevbarns commented
🚀

2024-05-21 07:57 UTC, remy-auricoste requested changes

2024-05-21 07:57 UTC, remy-auricoste commented on server/src/security/accessTokenService.ts
> +export type IApplicationForAccessToken = { type: "application"; company_siret: string; email: "" } | { type: "application"; jobId: string; email: "" }
Le type IApplicationForAccessToken sert à identifier la personne qui fait l'action, pas à inclure les données permettant de définir quelle action peut être faite. Les champs company_siret et jobId ne doivent pas être dans cet objet

2024-05-21 07:57 UTC, remy-auricoste commented on server/src/services/appLinks.service.ts
> +      options: {
c'est ici qu'il faut définir à quel candidature le token a accès

2024-05-21 07:57 UTC, remy-auricoste commented on server/src/services/application.service.ts
> +type ILbaJob = { type: LBA_ITEM_TYPE.RECRUTEURS_LBA; job: ILbaCompany; recruiter: null } | { type: LBA_ITEM_TYPE.OFFRES_EMPLOI_LBA; job: IJob; recruiter: IRecruiter }
```suggestion
type ILbaJob = { type: LBA_ITEM_TYPE.RECRUTEURS_LBA; job: ILbaCompany } | { type: LBA_ITEM_TYPE.OFFRES_EMPLOI_LBA; job: IJob; recruiter: IRecruiter }
```

2024-05-21 07:57 UTC, remy-auricoste commented on server/src/services/application.service.ts
> +  let LbaJob: ILbaJob = { type: null as any, job: null as any, recruiter: null }
```suggestion
  let LbaJob: ILbaJob
```

2024-05-21 07:57 UTC, remy-auricoste commented on server/src/services/application.service.ts
> +const checkUserApplicationCountV2 = async (applicantEmail: string, LbaJob: ILbaJob, caller?: string): Promise<void> => {
Quel est l'intérêt de copier ce code ?

2024-05-21 07:57 UTC, remy-auricoste commented on ui/components/ItemDetail/CandidatureLba/services/submitCandidature.ts
> +    await axios.post(candidatureApi, payload, { headers: { Authorization: `Bearer ${LbaJob.token}` } })
Est ce qu'on peut plutôt utiliser `apiPost` ?

2024-05-21 07:57 UTC, remy-auricoste commented on ui/services/extractCandidatureParams.ts
> -export default function extractCandidatureParams(applicant_h, company_h, jobLabel = null, caller) {
:heart:

2024-05-22 09:22 UTC, merged