fix: lbac 2115: update mails
mission-apprentissage/labonnealternance pull request #1302
Opened 2024-06-18 15:36 UTC by remy-auricoste

2024-06-18 15:40 UTC, remy-auricoste commented
🚀

2024-06-18 16:08 UTC, alanlr requested changes
j'ai pas encore tout fait. mais j'ai déjà qq remarques.

2024-06-18 16:08 UTC, alanlr commented on server/static/templates/mail-bienvenue-entreprise-sans-offre.mjml.ejs
> +              Accédez à votre espace et publiez vos offres en quelques clics afin de les diffuser au près des jeunes sur les sites : Parcoursup, Affelnet, 1jeune1solution, et La bonne alternance.
typo: auprès et pas "au près"

2024-06-18 16:08 UTC, alanlr commented on server/static/templates/mail-bienvenue-entreprise-sans-offre.mjml.ejs
> +            <mj-button href="<%= data.confirmation_url %>" align="center" background-color="#000091" border-radius="0px" color="#ffffff" css-class="button" font-family="Arial, Helvetica, Verdana, san
href vide. voulu avec le mj-button ?

2024-06-18 16:08 UTC, alanlr commented on server/static/templates/mail-bienvenue-entreprise-sans-offre.mjml.ejs
> +<br/><%= data.confirmation_url %>
pas de balise a pour faciliter le collage  ?

2024-06-18 16:08 UTC, alanlr commented on server/static/templates/mail-candidature-spontanee.mjml.ejs
> +              <span style="font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 16px; line-height: 28px; font-weight: 700; color: #161616;"><%= data.applicant_first_name %> <%= data.applica
span vide. le texte donne l'impression qu'il y manque quelque chose

2024-06-19 06:51 UTC, alanlr commented on server/static/templates/mail-candidature.mjml.ejs
> +              Vous recrutez un<span style="font-family: Arial, Helvetica, Verdana, sans-serif; font-weight: 700;">·</span>e alternant<span style="font-family: Arial, Helvetica, Verdana, sans-serif; f
Est ce vraiment nécessaire de mettre en gras les "." des "un.e" ? ;-)

2024-06-19 07:07 UTC, alanlr requested changes
encore une partielle. me reste deux fichiers à review

2024-06-19 07:07 UTC, alanlr commented on server/static/templates/mail-expiration-offres.mjml.ejs
> +            <mj-image align="left" alt="Image" css-class="image" href="#" src="<%= data.images.logoRf %>" width="89px">
pourquoi un href ici ? et la balise fermante peut être collée à l'ouvrante ou  peut être autoclose (si c'est fonctionnel ici). Idem plus bas

2024-06-19 07:07 UTC, alanlr commented on server/static/templates/mail-expiration-offres.mjml.ejs
> +            <mj-image align="left" alt="Image" css-class="image" href="#" padding="17px 0px 17px 0px" src="<%= data.images.logoLba %>" width="160px">
alt devrait être remplacé par une phrase plus explicite ou être à "" si c'est de la pur décoration

2024-06-19 07:07 UTC, alanlr commented on server/static/templates/mail-expiration-offres.mjml.ejs
> +            <mj-button align="center" background-color="#000091" border-radius="0px" border="1px solid #000091" color="#ffffff" css-class="button" font-family="Arial, Helvetica, Verdana, sans-serif"
href vide ?

2024-06-19 07:07 UTC, alanlr commented on server/static/templates/mail-expiration-offres.mjml.ejs
> +            <mj-text align="left" color="#161616" css-class="text" font-family="Arial, Helvetica, Verdana, sans-serif" font-size="16px" font-weight="400" line-height="24px" padding="10px 0px 10px 0px
pas un lien / bouton ?

2024-06-19 07:07 UTC, alanlr commented on server/static/templates/mail-expiration-offres.mjml.ejs
espace entre balises ouvrante et fermante

2024-06-19 07:17 UTC, remy-auricoste commented on server/static/templates/mail-expiration-offres.mjml.ejs
> +            <mj-image align="left" alt="Image" css-class="image" href="#" src="<%= data.images.logoRf %>" width="89px">
c'était dans la template. Probablement à supprimer.

2024-06-19 08:13 UTC, remy-auricoste commented on server/static/templates/mail-bienvenue-entreprise-sans-offre.mjml.ejs
> +            <mj-button href="<%= data.confirmation_url %>" align="center" background-color="#000091" border-radius="0px" color="#ffffff" css-class="button" font-family="Arial, Helvetica, Verdana, san
Je le vois avec une valeur : `href="<%= data.confirmation_url %>"`

2024-06-19 08:13 UTC, remy-auricoste commented on server/static/templates/mail-bienvenue-entreprise-sans-offre.mjml.ejs
> +<br/><%= data.confirmation_url %>
c'était le design original

2024-06-19 08:14 UTC, remy-auricoste commented on server/static/templates/mail-candidature-spontanee.mjml.ejs
> +              <span style="font-family: Arial, Helvetica, Verdana, sans-serif; font-size: 16px; line-height: 28px; font-weight: 700; color: #161616;"><%= data.applicant_first_name %> <%= data.applica
je le supprime

2024-06-19 08:16 UTC, remy-auricoste commented on server/static/templates/mail-candidature.mjml.ejs
> +              Vous recrutez un<span style="font-family: Arial, Helvetica, Verdana, sans-serif; font-weight: 700;">·</span>e alternant<span style="font-family: Arial, Helvetica, Verdana, sans-serif; f
A voir avec Claire

2024-06-19 08:21 UTC, alanlr requested changes, later dismissed

2024-06-19 08:21 UTC, alanlr commented on server/static/templates/mail-nouvelle-offre-depot-simplifie.mjml.ejs
> +            <mj-button href="<%= data.confirmation_url %>" align="center" background-color="#000091" border-radius="0px" color="#ffffff" css-class="button" font-family="Arial, Helvetica, Verdana, san
2 fois href

2024-06-19 08:21 UTC, alanlr commented on server/static/templates/mail-nouvelle-offre-depot-simplifie.mjml.ejs
> +<br/>
c'est le linter qui colle tous ces <br /> en début de ligne. ce serait cool s'ils pouvaient être indentés en rapport avec la hiérarchie du balisage.

2024-06-19 08:21 UTC, alanlr commented on server/static/templates/mail-nouvelle-offre-depot-simplifie.mjml.ejs
> +              En savoir plus
pas de lien

2024-06-19 08:21 UTC, alanlr commented on server/static/templates/mail-nouvelle-offre-depot-simplifie.mjml.ejs
> +              [Nom du CFA]
?

2024-06-19 08:21 UTC, alanlr commented on server/static/templates/mail-nouvelle-offre-depot-simplifie.mjml.ejs
> +              En savoir plus
idem ci-dessus

2024-06-19 08:21 UTC, alanlr commented on server/static/templates/mail-nouvelle-offre-depot-simplifie.mjml.ejs
> +            <mj-text align="left" color="#161616" css-class="text" font-family="Arial, Helvetica, Verdana, sans-serif" font-size="16px" font-weight="400" line-height="28px" padding="10px 0px 10px 0px
même remarque sur le "."  en gras de "un.e" . ca me paraît surcharger le balisage pour du peu perceptible

2024-06-19 08:21 UTC, alanlr commented on server/static/templates/mail-nouvelle-offre.mjml.ejs
> +              [Nom du CFA]
même remarque que sur le template précédent. sur nom de cfa et lien en savoir plus qui n'ont pas l'air d'être transformés en valeurs réelles.

2024-06-19 08:21 UTC, alanlr commented on server/static/templates/mail-nouvelle-offre.mjml.ejs
> +              Vous recrutez un<span style="font-family: Arial, Helvetica, Verdana, sans-serif; font-weight: 700;">·</span>e alternant<span style="font-family: Arial, Helvetica, Verdana, sans-serif; f
un.e :)

2024-06-19 08:22 UTC, alanlr commented on server/static/templates/mail-bienvenue-entreprise-sans-offre.mjml.ejs
> +            <mj-button href="<%= data.confirmation_url %>" align="center" background-color="#000091" border-radius="0px" color="#ffffff" css-class="button" font-family="Arial, Helvetica, Verdana, san
le href est présent une deuxième fois avec href="#"

2024-06-19 08:31 UTC, remy-auricoste commented on server/static/templates/mail-bienvenue-entreprise-sans-offre.mjml.ejs
> +            <mj-button href="<%= data.confirmation_url %>" align="center" background-color="#000091" border-radius="0px" color="#ffffff" css-class="button" font-family="Arial, Helvetica, Verdana, san
je l'ai supprimé

2024-06-19 08:31 UTC, remy-auricoste commented on server/static/templates/mail-expiration-offres.mjml.ejs
> +            <mj-text align="left" color="#161616" css-class="text" font-family="Arial, Helvetica, Verdana, sans-serif" font-size="16px" font-weight="400" line-height="24px" padding="10px 0px 10px 0px
j'ai fixé

2024-06-19 08:35 UTC, remy-auricoste commented on server/static/templates/mail-nouvelle-offre-depot-simplifie.mjml.ejs
> +<br/>
le linter ne passe pas sur les mails

2024-06-19 08:36 UTC, remy-auricoste commented on server/static/templates/mail-nouvelle-offre-depot-simplifie.mjml.ejs
> +              [Nom du CFA]
les mises en relations ne sont pas affichées pour l'instant (cf notre discussion en stand up)

2024-06-19 08:55 UTC, remy-auricoste commented on server/static/templates/mail-nouvelle-offre-depot-simplifie.mjml.ejs
> +              En savoir plus
ça fait partie des délégations et donc ce n'est pas affiché

2024-06-19 14:57 UTC, alanlr commented on server/static/templates/mail-nouvelle-offre-depot-simplifie.mjml.ejs
> +              [Nom du CFA]
ok

2024-06-20 07:33 UTC, remy-auricoste commented
🚀

2024-06-20 08:55 UTC, remy-auricoste commented
🚀

2024-06-20 12:06 UTC, remy-auricoste commented
🚀

2024-06-20 12:52 UTC, remy-auricoste commented
🚀

2024-06-24 09:09 UTC, remy-auricoste commented
🚀

2024-06-24 09:33 UTC, remy-auricoste commented
🚀

2024-06-24 10:11 UTC, remy-auricoste commented
🚀

2024-06-24 15:07 UTC, remy-auricoste commented
🚀

2024-06-25 09:32 UTC, remy-auricoste commented
🚀

2024-06-25 12:27 UTC, remy-auricoste commented
🚀

2024-06-25 12:47 UTC, remy-auricoste commented
🚀

2024-06-25 15:31 UTC, remy-auricoste commented
🚀

2024-07-01 08:09 UTC, remy-auricoste commented
🚀

2024-07-02 08:30 UTC, alanlr approved these changes

2024-07-02 13:15 UTC, merged