Lbac 2156 cerfa demat
mission-apprentissage/labonnealternance pull request #1311
Opened 2024-06-25 09:35 UTC by remy-auricoste

https://mna-matcha.atlassian.net/jira/software/projects/LBA/boards/10?assignee=712020%3A805c2bc3-b985-42ea-9088-d8d83d9b3925&selectedIssue=LBA-2156

2024-06-25 09:47 UTC, remy-auricoste commented
🚀

2024-06-25 10:08 UTC, kevbarns requested changes, later dismissed
Problème de format de la carte en mobile 
![Capture d’écran 2024-06-25 à 12 07 32](https://github.com/mission-apprentissage/labonnealternance/assets/22106329/f5fdc86c-bdfc-4bb5-a022-bc498bd31c70)

2024-06-25 13:23 UTC, kevbarns commented
🚀

2024-06-25 13:38 UTC, kevbarns approved these changes

2024-06-26 11:49 UTC, kevbarns commented
🚀

2024-07-01 15:10 UTC, merged