feat: add jobOpportunity type
mission-apprentissage/labonnealternance pull request #1337
Opened 2024-07-05 13:48 UTC by kevbarns

- https://mna-matcha.atlassian.net/browse/LBA-2256

2024-07-15 08:08 UTC, kevbarns commented on server/src/http/controllers/jobs.controller.v2.ts
> +      const result = await getRecruteursLbaFromDB({ ...payload, romes: payload.romes as string[] })
Ici, si romes n'est pas forcé à string[] il est incompatible avec le type attendue car en mode RNCP, il peut être null ou undefined car je le rajoute ligne 498. Existe-t-il une meilleur solution ? faut-il splitter les routes RNCP / ROME ? 

typage : 
```js
export type IJobOpportunityRomeRncp = IJobOpportunityRome | (IJobOpportunityRncp & { romes?: string | null })
```

2024-07-15 08:23 UTC, remy-auricoste requested changes
:+1:  modulo le typage

2024-07-15 08:23 UTC, remy-auricoste commented on server/src/http/controllers/jobs.controller.v2.ts
> +    { schema: zRoutes.get["/jobs/recruteurs_lba"], onRequest: server.auth(zRoutes.get["/jobs/recruteurs_lba"]) },
Si tu utilises l'enum dans le path de la route, il faut aussi l'utiliser dans la définition des routes

2024-07-15 08:23 UTC, remy-auricoste commented on server/src/http/controllers/jobs.controller.v2.ts
> +      const result = await getRecruteursLbaFromDB({ ...payload, romes: payload.romes as string[] })
```suggestion
      const result = await getRecruteursLbaFromDB({ ...payload, romes: payload?.romes ?? [] })
```

2024-07-15 08:23 UTC, remy-auricoste commented on server/src/services/jobOpportunity.service.ts
> +  recruteursLba.map((recruteurLba) => {
```suggestion
  return recruteursLba.map((recruteurLba) => {
```

2024-07-15 08:23 UTC, remy-auricoste commented on server/src/services/jobOpportunity.service.ts
> +  return formattedResult
```suggestion
```

2024-07-15 08:23 UTC, remy-auricoste commented on server/src/services/lbacompany.service.ts
> +  const { romes, opco, opcoUrl, latitude, longitude } = params
```suggestion
export const getRecruteursLbaFromDB = async ({ radius = 10, romes, opco, opcoUrl, latitude, longitude }: IRecruteursLbaSearchParams): Promise<ILbaCompany[] | []> => {
```

2024-07-15 08:23 UTC, remy-auricoste commented on server/src/services/lbacompany.service.ts
> +  const query: any = {
A typer

2024-07-15 08:23 UTC, remy-auricoste commented on shared/routes/common.routes.ts
> +  querystring?: AnyZodObject | ZodUnion<Readonly<[AnyZodObject, ...AnyZodObject[]]>>
Ca ne devrait pas être nécessaire

2024-07-15 10:00 UTC, kevbarns commented on server/src/http/controllers/jobs.controller.v2.ts
> +    { schema: zRoutes.get["/jobs/recruteurs_lba"], onRequest: server.auth(zRoutes.get["/jobs/recruteurs_lba"]) },
ça ne fonctionne pas malheureusement, il ne résout pas le path

2024-07-15 10:02 UTC, kevbarns commented on shared/routes/common.routes.ts
> +  querystring?: AnyZodObject | ZodUnion<Readonly<[AnyZodObject, ...AnyZodObject[]]>>
l'union que j'utilise dans les querystring est un zod type et non un zod object

2024-07-22 13:59 UTC, remy-auricoste approved these changes

2024-07-22 17:26 UTC, merged