fix: lbac 2347: fix appointments.applicant_id type to objectId
mission-apprentissage/labonnealternance pull request #1367
Opened 2024-07-18 13:02 UTC by remy-auricoste

ticket : https://mna-matcha.atlassian.net/jira/software/projects/LBA/boards/10?selectedIssue=LBA-2347

2024-07-19 09:00 UTC, kevbarns requested changes, later dismissed
Il manque des conversions :
- https://github.com/mission-apprentissage/labonnealternance/blob/d1bdabc2050ae4cee6a0a7317e130f140c921513/server/src/http/controllers/appointmentRequest.controller.ts#L212
- https://github.com/mission-apprentissage/labonnealternance/blob/d1bdabc2050ae4cee6a0a7317e130f140c921513/server/src/http/controllers/appointmentRequest.controller.ts#L259
Supprimer la fonction suivante au profit d'un appel mongoDB direct à l'appel précédent : 
- https://github.com/mission-apprentissage/labonnealternance/blob/d3d9866c2d47ff3e4aadca0099e4f8176af6c217/server/src/services/user.service.ts#L41

2024-07-19 09:00 UTC, kevbarns commented on server/src/jobs/rdv/oneTimeJob/fixDuplicateUsers.ts
> +      await getDbCollection("appointments").updateMany({ applicant_id: group._id }, { $set: { applicant_id: userToKeep?._id } })
Est-ce que ce job sera joué à nouveau ? je pense qu'il peut être supprimé

2024-07-19 12:33 UTC, kevbarns commented
migration = interruption de service, prévoir la MEP le matin avant 8h ou le soir après 19h

2024-07-22 14:56 UTC, remy-auricoste commented on server/src/jobs/rdv/oneTimeJob/fixDuplicateUsers.ts
> +      await getDbCollection("appointments").updateMany({ applicant_id: group._id }, { $set: { applicant_id: userToKeep?._id } })
j'ai supprimé la commande

2024-07-24 17:29 UTC, merged