feat: LBA-2174 ne pas afficher prdv si déjà postulé - accès localstorage sans hook
mission-apprentissage/labonnealternance pull request #1425
Opened 2024-08-14 15:50 UTC by alanlr

2024-08-14 15:55 UTC, alanlr commented
🚀

2024-08-20 06:40 UTC, kevbarns requested changes

2024-08-20 06:40 UTC, kevbarns commented on ui/components/ItemDetail/ItemDetailServices/ItemDetailApplicationStatus.tsx
> +const getAPostuleMessage = (type, applicationDate, mb, mt) => {
manque le typage

2024-08-20 06:40 UTC, kevbarns commented on ui/components/ItemDetail/ItemDetailServices/ItemDetailApplicationStatus.tsx
> +  return window.localStorage.getItem(`application-${item.ideaType}-${item.id}`) !== null
ça serait bien de faire un util pour get/set le localStorage

2024-08-20 06:40 UTC, kevbarns commented on ui/components/RDV/DemandeDeContact.tsx
> +        window.localStorage.setItem(`application-formation-${props.context.cle_ministere_educatif}`, Date.now().toString())
utils

2024-08-20 13:16 UTC, alanlr commented
🚀

2024-08-21 07:11 UTC, kevbarns approved these changes

2024-08-21 08:37 UTC, merged