feat: LBA-2458 gestion des computed_jobs_partners annulés
mission-apprentissage/labonnealternance pull request #1491
Opened 2024-09-05 12:47 UTC by alanlr

https://mna-matcha.atlassian.net/jira/software/projects/LBA/boards/10?assignee=70121%3A6a19a785-d6a8-4edc-8f66-e809f80d5a2e%2Cunassigned&selectedIssue=LBA-2458

2024-09-05 13:12 UTC, remy-auricoste approved these changes

2024-09-05 14:10 UTC, kevbarns requested changes
Ok pour le renommage de `partner` en `partner_label`, cc @moroine

2024-09-05 14:10 UTC, kevbarns commented on server/src/jobs/offrePartenaire/importFromComputedToJobsPartners.ts
> +  const cursor = await getDbCollection("computed_jobs_partners").find({ validated: true }).project({ _id: 0, validated: 0, errors: 0 }).stream()
si c'est un stream c'est pas un cursor

2024-09-05 14:10 UTC, kevbarns commented on server/tests/utils/jobsPartners.test.utils.ts
> +}
La création d'object dois se faire selon le nouveau modèle, `fixture` placé dans le `shared/fixture` ou tu trouvera des exemples. Zod fait mal les choses malheureusement.

2024-09-05 14:10 UTC, kevbarns commented on shared/models/address.model.ts
> +    type: z.literal("Point"),
laisse string, à l'avenir ça serait bien de gérer autre chose que des Points (i.e Polygon)

2024-09-06 13:06 UTC, alanlr commented on shared/models/address.model.ts
> +    type: z.literal("Point"),
c'est un autre type. ici on est spécifiquement dans ZPoint

2024-09-10 12:57 UTC, closed without merging