fix: LBA-2124 restauration contrôle de validité offre sur sendapplicationv2
mission-apprentissage/labonnealternance pull request #1516
Opened 2024-09-18 09:02 UTC by alanlr

https://tableaudebord-apprentissage.atlassian.net/browse/LBA-2124

2024-09-18 09:18 UTC, remy-auricoste approved these changes

2024-09-18 13:13 UTC, alanlr commented
:rocket:

2024-09-18 13:48 UTC, alanlr commented
:rocket:

2024-09-18 14:52 UTC, kevbarns requested changes

2024-09-18 14:52 UTC, kevbarns commented on server/tests/utils/job.test.utils.ts
> +//getDbCollection("referentielromes").insertOne(savedFiche)
Ce fichier doit être deux fixture séparé, referentielRome & jobs dans le dossier `shared/fixture`

2024-09-18 14:52 UTC, kevbarns commented on server/src/services/application.service.test.ts
> +})
Manque un test valide non ?

2024-09-18 15:46 UTC, alanlr commented on server/src/services/application.service.test.ts
> +})
laissé de côté pour l'instant. dans l'absolu il manque plein de tests sur le sujet des candidatures.

2024-09-23 07:36 UTC, kevbarns approved these changes

2024-09-23 14:06 UTC, alanlr commented
:rocket:

2024-09-23 15:35 UTC, alanlr commented
:rocket:

2024-09-23 16:42 UTC, merged