feat: lba-834 enquete feature suivi candidatures
mission-apprentissage/labonnealternance pull request #1537
Opened 2024-09-27 12:13 UTC by guilletmarion

Demander aux recruteurs s'ils seraient intéressés par une feature de suivi des candidature grâce au bandeau bleu

https://tableaudebord-apprentissage.atlassian.net/browse/LBA-834

2024-09-27 12:39 UTC, guilletmarion commented
🚀

2024-09-27 13:13 UTC, guilletmarion commented
🚀

2024-09-27 14:17 UTC, kevbarns commented
🚀

2024-09-27 14:36 UTC, guilletmarion commented
je peux voir pourquoi les tests cypress plantent ?

2024-09-30 13:46 UTC, kevbarns commented
@guilletmarion le lien fait sortir du site, il faut rajouter la prop `isExternal`

2024-09-30 13:47 UTC, kevbarns requested changes

2024-09-30 13:47 UTC, kevbarns commented on ui/components/InfoBanner/InfoBanner.tsx
> +    <Link textDecoration="underline" href="https://tally.so/r/3Xq19z">
```suggestion
    <Link textDecoration="underline" href="https://tally.so/r/3Xq19z" isExternal>
```

2024-09-30 14:31 UTC, guilletmarion commented
ah mais mince, je l'avais fait au mauvais endroit ..
<img width="494" alt="image" src="https://github.com/user-attachments/assets/20060a31-211b-4176-9cbf-ae4c38a6bbc2">

2024-10-02 09:37 UTC, kevbarns commented
🚀

2024-10-02 10:12 UTC, guilletmarion commented
@kevbarns le lien ne s'ouvre pas dans un nouvel onglet, sais-tu ce qui pêche ?

Testable sur la page https://1537.labonnealternance-preview.apprentissage.beta.gouv.fr/espace-pro/authentification en cliquant sur le lien entouré sur l'image ci-dessous 
<img width="688" alt="image" src="https://github.com/user-attachments/assets/f7a2501c-d571-4afe-bca3-2bbfe316f940">

2024-10-07 08:07 UTC, kevbarns commented
🚀

2024-10-07 08:32 UTC, guilletmarion commented
@kevbarns le bandeau a carrément disparu de l'espace recruteur là ..

2024-10-07 16:01 UTC, closed without merging