feat: LBA-2137 LBA-2139 tracking referer et utm
mission-apprentissage/labonnealternance pull request #1556
Opened 2024-10-03 12:13 UTC by alanlr

https://tableaudebord-apprentissage.atlassian.net/jira/software/projects/LBA/boards/14?assignee=712020%3A9a003bb4-d766-4edc-b4ab-ecd6529e3353%2Cunassigned&selectedIssue=LBA-2137

et

https://tableaudebord-apprentissage.atlassian.net/jira/software/projects/LBA/boards/14?assignee=712020%3A9a003bb4-d766-4edc-b4ab-ecd6529e3353%2Cunassigned&selectedIssue=LBA-2139

2024-10-03 15:29 UTC, alanlr commented
:rocket:

2024-10-03 15:43 UTC, remy-auricoste requested changes

2024-10-03 15:43 UTC, remy-auricoste commented on server/src/services/application.service.ts
> +    sendApplicationV2
```suggestion
```

2024-10-07 06:54 UTC, remy-auricoste approved these changes

2024-10-07 08:06 UTC, kevbarns approved these changes

2024-10-07 08:06 UTC, kevbarns commented on shared/models/trafficSources.model.ts
> +export const ZTrafficType = extensions.buildEnum(TrafficType)
export non utilisé à retirer

2024-10-07 13:07 UTC, merged