fix: marker mapbox non affichés sur un niveau de zoom
mission-apprentissage/labonnealternance pull request #157
Opened 2023-01-02 17:15 UTC by alanlr

Bug aléatoire. Utilisation d'un hack pour réduire les occurences d'apparition du bug.

Diverses améliorations sur le chargement des composants de la carte.

2023-01-03 14:07 UTC, bdavidxyz requested changes

2023-01-03 14:07 UTC, bdavidxyz commented on ui/components/SearchForTrainingsAndJobs/services/searchForTrainings.js
> +          centerMapOnTraining: hasLocation ?? false,
Bizarre. hasLocation est déjà un booléen, donc `centerMapOnTraining: hasLocation,` suffit

2023-01-03 14:07 UTC, bdavidxyz commented on ui/utils/mapTools.js
> +            if (!e.originalEvent.STOP) {
peut être simplifié en un seul "if" : `if (!e?.originalEvent?.STOP) {`

2023-01-03 14:22 UTC, alanlr commented on ui/components/SearchForTrainingsAndJobs/services/searchForTrainings.js
> +          centerMapOnTraining: hasLocation ?? false,
oui en effet j'avais lu en vitesse son affectation et supposé à tord qu'il pouvait être à nul

2023-01-03 14:22 UTC, alanlr commented on ui/utils/mapTools.js
> +            if (!e.originalEvent.STOP) {
non car sinon le test renverra true si même quand originalEvent n'existe pas alors qu'il doit exister.

2023-01-03 14:34 UTC, bdavidxyz commented on ui/utils/mapTools.js
> +            if (!e.originalEvent.STOP) {
ok

2023-01-03 15:58 UTC, bdavidxyz approved these changes

2023-01-03 16:31 UTC, merged

2023-03-14 15:19 UTC, kevbarns commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.0.0)
- `v1.0.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: