feat: LBA-1429 récupération context bouton prdv par requête get
mission-apprentissage/labonnealternance pull request #1593
Opened 2024-10-16 15:57 UTC by alanlr

https://tableaudebord-apprentissage.atlassian.net/jira/software/projects/LBA/boards/14?assignee=712020%3A9a003bb4-d766-4edc-b4ab-ecd6529e3353&selectedIssue=LBA-1429

remontée en prio pour remplacement de requête post par requête get . cf rapport ey

2024-10-22 09:00 UTC, kevbarns requested changes
- check `shared/routes/appointments.routes.v2.ts` pour utiliser le modèle zod `ZAppointmentContextApi` pour ta route GET. 
 - tu peux certainement utiliser `findElligibleTrainingForAppointmentV2` du coup

2024-10-22 09:00 UTC, kevbarns commented on server/src/http/controllers/appointmentRequest.controller.ts
> +    "/appointment/context",
/appointment (pour matcher la V2)

2024-10-22 09:00 UTC, kevbarns commented on server/src/services/eligibleTrainingsForAppointment.service.ts
> +  return await getEtfaContext(eligibleTrainingsForAppointment, referrerObj.name)
`getAppointmentContext`

2024-10-24 06:41 UTC, alanlr commented
on passe la POST v2 en GET histoire d'être pleinement raccord ?

2024-11-04 09:09 UTC, remy-auricoste commented on ui/components/ItemDetail/TrainingDetail.tsx
> +    retry: false,
Pourquoi supprimer le retry ? Ca aide la navigation dans le contexte d'une connectivité instable

2024-11-07 13:51 UTC, remy-auricoste approved these changes

2024-11-12 15:04 UTC, merged