fix: LBA-2180 sécuriser transmission email sur formulaire de désinscription
mission-apprentissage/labonnealternance pull request #1598
Opened 2024-10-18 14:20 UTC by alanlr

https://tableaudebord-apprentissage.atlassian.net/jira/software/projects/LBA/boards/14?assignee=712020%3A9a003bb4-d766-4edc-b4ab-ecd6529e3353&selectedIssue=LBA-2180

2024-10-22 08:50 UTC, kevbarns requested changes
Il faut plutôt protéger la route `/unsubscribe` à l'aide d'un token dédié à la route qui contient l'ID de l'application généré à partir du service `appLink.service.ts`. Tu déchiffres ensuite le token dans le controller pour les informations nécessaires.

2024-10-24 09:24 UTC, kevbarns approved these changes
vu en call, on conserve cette solution pour le moment

2024-10-24 12:08 UTC, alanlr commented
:rocket:

2024-10-24 15:04 UTC, alanlr commented
:rocket:

2024-10-28 18:05 UTC, merged