feat(lba-2146): Invalidation du computed si la société est fermée
mission-apprentissage/labonnealternance pull request #1642
Opened 2024-11-13 14:52 UTC by alanlr

2024-11-13 14:53 UTC, alanlr commented
:rocket:

2024-11-13 15:23 UTC, alanlr commented
:rocket:

2024-11-13 15:33 UTC, remy-auricoste requested changes

2024-11-13 15:33 UTC, remy-auricoste commented on server/src/jobs/offrePartenaire/fillSiretInfosForPartners.ts
> +      }
```suggestion
      if (data?.etat_administratif === "F") {
        throw internal(BusinessErrorCodes.CLOSED)
      }
```

2024-11-14 11:20 UTC, alanlr commented
:rocket:

2024-11-14 13:55 UTC, remy-auricoste commented on server/src/jobs/offrePartenaire/fillFieldsForPartnersFactory.ts
> +export const fillFieldsForPartnersFactory = async <SourceFields extends keyof IJobsPartnersOfferPrivate, FilledFields extends keyof IJobsPartnersOfferPrivate | "job_validity">({
```suggestion
export const fillFieldsForPartnersFactory = async <SourceFields extends keyof IJobsPartnersOfferPrivate, FilledFields extends keyof IJobsPartnersOfferPrivate>({
```

2024-11-14 14:03 UTC, remy-auricoste commented on server/src/jobs/offrePartenaire/fillSiretInfosForPartners.test.ts
> +  })
```suggestion
```
Le test est déjà présent plus haut ?

2024-11-14 14:03 UTC, remy-auricoste commented on shared/models/jobsPartnersComputed.model.ts
> +  VALID = "VALID",
```suggestion
```
Je pense que les 2 valeurs ont le même sens : il n y a pas d erreur empêchant la publication du job.
Le job est valide et sera publié jusqu'à preuve du contraire.
On pourrait donc les supprimer et mettre le champ à vide et ne le remplir que si il y a une erreur business qui empêche la publication. On pourrait alors renommer le champ en `job_business_error` ou `business_error`

2024-11-14 14:03 UTC, remy-auricoste commented on server/src/jobs/offrePartenaire/validateComputedJobPartners.ts
> +            }
```suggestion
       counters.success++
```
Le typage garantit que `validated = true` tout le temps ici

2024-11-14 14:26 UTC, alanlr commented on server/src/jobs/offrePartenaire/fillFieldsForPartnersFactory.ts
> +export const fillFieldsForPartnersFactory = async <SourceFields extends keyof IJobsPartnersOfferPrivate, FilledFields extends keyof IJobsPartnersOfferPrivate | "job_validity">({
job_validity n'est pas dans IJobsPartnersOfferPrivate. ca couine sans l'ajout ici

2024-11-14 14:28 UTC, alanlr commented on server/src/jobs/offrePartenaire/validateComputedJobPartners.ts
> +            }
en effet, c'est un reliquat de ma première version que j'ai oublié d'enlever

2024-11-14 15:13 UTC, remy-auricoste commented on server/src/jobs/offrePartenaire/fillFieldsForPartnersFactory.ts
> +export const fillFieldsForPartnersFactory = async <SourceFields extends keyof IJobsPartnersOfferPrivate, FilledFields extends keyof IJobsPartnersOfferPrivate | "business_error">({
```suggestion
export const fillFieldsForPartnersFactory = async <SourceFields extends keyof IJobsPartnersOfferPrivate, FilledFields extends keyof IJobsPartnersOfferPrivate>({
```
business_error fait déjà partie de keyof IJobsPartnersOfferPrivate

2024-11-14 15:15 UTC, remy-auricoste approved these changes

2024-11-14 15:22 UTC, alanlr commented on server/src/jobs/offrePartenaire/fillFieldsForPartnersFactory.ts
> +export const fillFieldsForPartnersFactory = async <SourceFields extends keyof IJobsPartnersOfferPrivate, FilledFields extends keyof IJobsPartnersOfferPrivate | "business_error">({
chez moi ça provoque immédiatement des erreurs dans fillSiretInfosForPartners.ts

2024-11-14 15:40 UTC, kevbarns approved these changes

2024-11-14 15:53 UTC, merged