feat(LBA-2171): émission des contacts vers Brevo
mission-apprentissage/labonnealternance pull request #1653
Opened 2024-11-18 13:56 UTC by alanlr

2024-11-18 15:01 UTC, remy-auricoste requested changes

2024-11-18 15:01 UTC, remy-auricoste commented on server/src/jobs/brevoContacts/sendContactsToBrevo.ts
> +  })
Je pense qu'il vaudrait mieux utiliser un librairie csv pour s'assurer du bon format.
Ici, les caractères spéciaux ne sont pas échappés

2024-11-19 16:57 UTC, kevbarns requested changes

2024-11-19 16:57 UTC, kevbarns commented on server/src/jobs/brevoContacts/sendContactsToBrevo.ts
> +  job_count?: string | null | undefined
```suggestion
  entreprise_enseigne?: string | null
  entreprise_raison_sociale?: string | null
  cfa_enseigne?: string | null
  cfa_raison_sociale?: string | null
  job_count?: string | null
```
? = undefined

2024-11-19 16:57 UTC, kevbarns commented on server/src/jobs/brevoContacts/sendContactsToBrevo.ts
> +  })
tu as csv-stringify sur le server pour t'aider : tu peux recréer un objet avec les header en paramètres et leurs valeurs associées, puis utiliser cet objet pour générer un CSV. check `server/src/jobs/partenaireExport/exportToFranceTravail.ts`

2024-11-19 16:57 UTC, kevbarns commented on server/src/jobs/brevoContacts/sendContactsToBrevo.ts
> +  const cursor =
les ternaires c'est bien quand c'est court 😮

2024-11-19 16:57 UTC, kevbarns commented on server/src/jobs/brevoContacts/sendContactsToBrevo.ts
> +      ? await ensureInitialization()
pourquoi tu n'utilises pas directement `getDbCollection` qui implémente déjà `ensureInitialization().db()` ?

2024-11-19 16:57 UTC, kevbarns commented on server/src/jobs/brevoContacts/sendContactsToBrevo.ts
> +const postToBrevo = async (contacts: IBrevoContact[]) => {
Ici j'aurai ajouté un try/catch et throw le détail de l'erreur, voir également un envoi sur sentry

2024-11-21 14:35 UTC, remy-auricoste commented on server/src/commands.ts
> +program
Est ce que tu peux migrer la commande vers `server/src/jobs/simpleJobDefinitions.ts` stp ?

2024-11-21 14:35 UTC, remy-auricoste commented on server/src/jobs/brevoContacts/sendContactsToBrevo.ts
> +const CONTACT_LIST = 6
Je mettrais ça plutôt en variable d'environnement

2024-11-21 14:35 UTC, remy-auricoste commented on server/src/jobs/brevoContacts/sendContactsToBrevo.ts
> +              email: "$user_email",
Attention, ce champ n'est pas fiable. Dans le cas d'un cfa qui saisit une entreprise, il peut mettre ce qu'il veut

2024-11-21 14:35 UTC, remy-auricoste commented on server/src/jobs/brevoContacts/sendContactsToBrevo.ts
> +        },
cette jointure est normalement déjà faite sur rolemanagement360

2024-11-21 14:35 UTC, remy-auricoste commented on server/src/jobs/brevoContacts/sendContactsToBrevo.ts
> +  })
Tu peux utiliser `streamGroupByCount` qui fait exactement la même chose

2024-11-21 15:05 UTC, alanlr commented on server/src/jobs/brevoContacts/sendContactsToBrevo.ts
> +              email: "$user_email",
ok

2024-11-21 15:45 UTC, alanlr commented on server/src/jobs/brevoContacts/sendContactsToBrevo.ts
> +        },
ok bien vu ces étapes sont useless avec le match sur entreprise. j'avais commencé ma réflexion à partir des data d'un cfa

2024-11-26 14:19 UTC, remy-auricoste approved these changes

2024-11-27 13:01 UTC, merged