fix(lbac-2247): fix typage idcc
mission-apprentissage/labonnealternance pull request #1656
Opened 2024-11-19 09:20 UTC by remy-auricoste

https://tableaudebord-apprentissage.atlassian.net/jira/software/projects/LBA/boards/14?selectedIssue=LBA-2247

2024-11-19 10:32 UTC, alanlr approved these changes

2024-11-19 10:32 UTC, alanlr requested changes
commentaire hâtif de ma part (edité)

2024-11-19 10:33 UTC, alanlr approved these changes

2024-11-19 16:39 UTC, kevbarns approved these changes

2024-11-20 08:16 UTC, remy-auricoste commented
🚀

2024-11-20 12:05 UTC, merged