Feat: send all email from same address
mission-apprentissage/labonnealternance pull request #170
Opened 2023-01-05 15:50 UTC by kevbarns

https://mna-matcha.atlassian.net/browse/LBAC-719 + https://mission-apprentissage.slack.com/archives/C037H6Y44S2/p1672933356162669

2023-01-05 15:58 UTC, alanlr commented on server/src/config.js
> -  rdvEmail: "rdv_apprentissage@apprentissage.beta.gouv.fr",
En plus de la suppression on pourrait aussi ajouter une variable lbaNoReplyEmail: "nepasre...." et l'utiliser à la place des valeurs en dur ?

2023-01-05 17:14 UTC, kevbarns commented on server/src/config.js
> -  rdvEmail: "rdv_apprentissage@apprentissage.beta.gouv.fr",
Bonne idée !

2023-01-05 17:16 UTC, kevbarns commented on server/src/config.js
> -  rdvEmail: "rdv_apprentissage@apprentissage.beta.gouv.fr",
j'ai aussi mis à jour/simplifié la création de l'instance mailer

2023-01-06 08:54 UTC, alanlr requested changes

2023-01-06 08:54 UTC, alanlr commented on server/src/http/routes/etablissement.js
> +          to: "nepasrepondre@apprentissage.beta.gouv.fr",
oubli de report de la nouvelle variable en config

2023-01-06 08:54 UTC, alanlr commented on server/src/service/applications.js
> +    to: "nepasrepondre@apprentissage.beta.gouv.fr",
idem

2023-01-06 09:35 UTC, merged

2023-03-14 15:19 UTC, kevbarns commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.0.0)
- `v1.0.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: