feat(lba-2262): évolution réponse à candidat
mission-apprentissage/labonnealternance pull request #1725
Opened 2024-12-19 14:26 UTC by alanlr

https://tableaudebord-apprentissage.atlassian.net/jira/software/projects/LBA/boards/14?assignee=712020%3A9a003bb4-d766-4edc-b4ab-ecd6529e3353&selectedIssue=LBA-2262

2024-12-26 08:04 UTC, alanlr commented
:rocket:

2024-12-26 10:07 UTC, kevbarns requested changes
Vu ensemble : utiliser la collection `applicants_email_logs` provenant du ticket 2266 et rapatrier le champ intention dans applications, la collection `applicants_email_logs` ne doit pas contenir de données autre que l'envoie des emails

2024-12-26 10:07 UTC, kevbarns commented on server/src/http/controllers/application.controller.ts
> +  )
La route ici permet de récupérer l'intention de recrutement c'est ça ? Dans ce cas là, plutôt partir sur `/application/intention/:id`

2024-12-26 10:07 UTC, kevbarns commented on server/src/http/controllers/application.controller.ts
> +
`application/intention/cancel/:id`

2024-12-26 10:07 UTC, kevbarns commented on server/src/services/appLinks.service.ts
> +      }),
à mettre à jour avec le nommage des controlleurs et routes

2024-12-26 10:07 UTC, kevbarns commented on server/src/services/application.service.ts
> +}
Je pense que ça serait mieux que cette fonction retourne le `IJobOrCompany` pour être consistent avec le reste du service, on pourra y ajouter les infos de la collection jobsPartners après coup et appeler la fonction `getJobApplication` ou dans le style, et je ferai une autre fonction (hors scope de la PR) pour récupérer le job par le nom de la collection (cf. sendApplicationV2) L276/L302 appelé ± `getJobApplicationFromCollectionName`

2024-12-26 10:07 UTC, kevbarns commented on server/src/services/application.service.ts
> +    const intentionCursor = await getDbCollection("recruiter_intention_mails").find({}).toArray()
c'est plus un curseur si tu mets un toArray()

2024-12-26 10:07 UTC, kevbarns commented on server/src/services/application.service.ts
> +}
Pour éviter un job trop long ça serait bien d'appliquer le même processus que pour l'envoi des candidatures, un job timé dans le temps, comme ça il peut tourner 24/7

2024-12-26 10:07 UTC, kevbarns commented on shared/constants/application.ts
>  }
On peut passer les valeurs en majuscule ?

2024-12-26 10:07 UTC, kevbarns commented on shared/models/recruiterIntentionMail.model.ts
> +  intention: extensions.buildEnum(ApplicationIntention),
Rapatrier le champs dans application, `intention_status` et utiliser la collection `applicants_email_logs` provenant du ticket 2266

2024-12-29 13:40 UTC, alanlr commented on server/src/http/controllers/application.controller.ts
> +  )
non elle permet de récupérer les informations en vue d'enregistrer l'intention. mais pourquoi pas ça fera plus léger.

2024-12-29 17:04 UTC, alanlr commented on shared/models/recruiterIntentionMail.model.ts
> +  intention: extensions.buildEnum(ApplicationIntention),
Ca ne me paraît pas avoir le même usage. Les données de recruiterIntentionMail n'ont pas vocation à persister après envoi de l'intention

2025-01-06 14:16 UTC, alanlr commented
:rocket:

2025-01-08 14:58 UTC, alanlr commented
:rocket:

2025-01-15 16:01 UTC, kevbarns approved these changes

2025-01-15 16:39 UTC, merged