WIP: feat: emails
mission-apprentissage/labonnealternance pull request #176
Opened 2023-01-11 18:15 UTC by rimiti

## Objectif

Cette PR a pour cible de:

- Ticket #631
- Ticket #630
- Ticket #614

2023-01-11 18:50 UTC, kevbarns requested changes

2023-01-11 18:50 UTC, kevbarns commented on server/src/config.js
> +  matchaEmail: "matcha@apprentissage.beta.gouv.fr",
le `matchaEmail` a déjà été retiré normalement.
- renommer `email` en `campaignEmail` (c'est voulu d'utiliser ce mail plutôt que le `transactionalEmail` ?)

2023-01-11 19:03 UTC, alanlr commented on server/src/assets/templates/mail-cfa-optout-activated.mjml.ejs
> +                    <b>Vos offres d’emploi et vos formations sont visibles sur les sites d’alternance les plus visités par les candidats</b>, notamment La bonne alternance, Affelnet, Parcoursup, 1jeu
il y a un drôle de caractère avant "Les informations ..." pas de risque de mauvaise interprétation sur des clients web ?

2023-01-11 19:06 UTC, alanlr commented on server/src/assets/templates/mail-cfa-optout-activated.mjml.ejs
> +                    à <a href="mailto:labonnealternance@apprentissage.beta.gouv.fr" class="grey">labonnealternance@apprentissage.beta.gouv.fr</a> afin de nous permettre d’effectuer ces modifications.
passage de l'email en param ?

2023-01-11 19:08 UTC, alanlr commented on server/src/assets/templates/mail-cfa-premium-activated-reminder.mjml.ejs
> +                    <b>Vos offres d’emploi et vos formations sont visibles sur les sites d’alternance les plus visités par les candidats</b>, notamment La bonne alternance, Affelnet, Parcoursup, 1jeu
caractère spécial idem fichier précédent

2023-01-11 19:09 UTC, alanlr commented on server/src/assets/templates/mail-cfa-premium-activated-reminder.mjml.ejs
> +                    à <a href="mailto:labonnealternance@apprentissage.beta.gouv.fr" class="grey">labonnealternance@apprentissage.beta.gouv.fr</a> afin de nous permettre d’effectuer ces modifications.
idem mise en param ?

2023-01-11 19:10 UTC, alanlr commented on server/src/assets/templates/mail-cfa-premium-activated.mjml.ejs
> +                    <b>Vos offres d’emploi et vos formations sont visibles sur les sites d’alternance les plus visités par les candidats</b>, notamment La bonne alternance, Affelnet, Parcoursup, 1jeu
caractère spécial

2023-01-11 19:11 UTC, alanlr commented on server/src/assets/templates/mail-cfa-premium-activated.mjml.ejs
> +                    à <a href="mailto:labonnealternance@apprentissage.beta.gouv.fr" class="grey">labonnealternance@apprentissage.beta.gouv.fr</a> afin de nous permettre d’effectuer ces modifications.
idem email param

2023-01-12 10:16 UTC, alanlr commented on server/src/assets/templates/mail-cfa-premium-invite-one-shot.mjml.ejs
> +                    Depuis le <b><%= data.etablissement.optOutActivatedAtDate %></b>, votre centre de formation est inscrit au service de prise de rendez-vous Apprentissage sur vos fiches formations
data.url

2023-01-12 10:23 UTC, alanlr commented on server/src/jobs/rdv/inviteEtablissementToOptOut.js
> +            template: mailTemplate["mail-cfa-optout-activated"],
pas besoin d'url et replyto ici ?

2023-01-12 10:26 UTC, alanlr commented on server/src/jobs/rdv/premiumInviteOneShot.js
> +        replyTo: config.publicEmail,
pas besoin d'url ?

2023-01-12 10:27 UTC, alanlr reviewed
des points à vérifier en commentaire

2023-01-12 10:37 UTC, merged

2023-03-14 15:19 UTC, kevbarns commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.0.0)
- `v1.0.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: