fix: [691] styles astuces
mission-apprentissage/labonnealternance pull request #186
Opened 2023-01-17 10:59 UTC by bdavidxyz

2023-01-17 14:19 UTC, alanlr requested changes

2023-01-17 14:19 UTC, alanlr commented on ui/components/SearchForTrainingsAndJobs/services/whispers.js
> +  return `<div class="gtmWhisper" style="margin-left: 25px; margin-right: 25px;margin-top: 25px; margin-bottom: 25px; text-align: left;">
on peut retirer gtmWhisper aussi vu que ça servait que pour analytics

2023-01-17 14:25 UTC, bdavidxyz commented on ui/components/SearchForTrainingsAndJobs/services/whispers.js
> +  return `<div class="gtmWhisper" style="margin-left: 25px; margin-right: 25px;margin-top: 25px; margin-bottom: 25px; text-align: left;">
ok je supprime gtmWhisperLink également? (qui est plus bas)

2023-01-17 14:33 UTC, alanlr approved these changes

2023-01-23 08:16 UTC, merged

2023-03-14 15:18 UTC, kevbarns commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.0.0)
- `v1.0.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: