Feat(611): update ETP workflow
mission-apprentissage/labonnealternance pull request #194
Opened 2023-01-23 10:25 UTC by kevbarns

https://mna-matcha.atlassian.net/browse/LBAC-611 --> voir ticket Jira

2023-01-23 13:38 UTC, alanlr approved these changes
Qq commentaires non bloquants

2023-01-23 13:38 UTC, alanlr commented on ui_espace_pro/src/components/Bandeau.jsx
> +            <Link href={lien} textDecoration="underline" isExternal>
un title ou aria-label parlant seraient le bienvenu ici :)

2023-01-23 13:38 UTC, alanlr commented on ui_espace_pro/src/pages/Formulaire/DepotRapide_Fin.jsx
> +          setTitle("Félicitations,<br>votre offre a bien été créée.<br>Elle sera publiée dès validation de votre compte.")
que ce soit ici ou dans d'autres emplacements, je trouverai ça utile de préciser que la validation se fait "par nos services" . mais c'est du wording :)

2023-01-23 13:40 UTC, kevbarns commented on ui_espace_pro/src/pages/Formulaire/DepotRapide_Fin.jsx
> +          setTitle("Félicitations,<br>votre offre a bien été créée.<br>Elle sera publiée dès validation de votre compte.")
justement elle est faite par l'OPCO normalement...

2023-01-23 13:41 UTC, kevbarns commented on ui_espace_pro/src/components/Bandeau.jsx
> +            <Link href={lien} textDecoration="underline" isExternal>
Alors manque de pot, il est utilisé nulle part et peut changer de destination car c'est un paramètre, je ne saurai quoi mettre

2023-01-23 13:41 UTC, merged

2023-01-23 13:43 UTC, bdavidxyz requested changes

2023-01-23 13:43 UTC, bdavidxyz commented on ui_espace_pro/src/pages/Formulaire/DepotRapide_Fin.jsx
> +          <Circle p={5} size="20px" bg="#E3E3FD" color="#000091" fontWeight="700">
color: 000091 c'est bluefrance.500

2023-01-23 14:26 UTC, kevbarns commented on ui_espace_pro/src/pages/Formulaire/DepotRapide_Fin.jsx
> +          <Circle p={5} size="20px" bg="#E3E3FD" color="#000091" fontWeight="700">
yes bien vu !

2023-03-14 15:18 UTC, kevbarns commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.0.0)
- `v1.0.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: