[432] Offres complètes
mission-apprentissage/labonnealternance pull request #224
Opened 2023-02-06 14:14 UTC by bdavidxyz

2023-02-07 15:35 UTC, alanlr requested changes

2023-02-07 15:35 UTC, alanlr commented on ui/components/SearchForTrainingsAndJobs/components/DuoContainer.js
> +          des offres combinant formation et emploi
le . doit être dans la balise text. il est en rouge également également sur le figma

2023-02-07 17:27 UTC, kevbarns approved these changes
👍

2023-02-07 17:28 UTC, merged

2023-03-14 15:16 UTC, kevbarns commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.0.0)
- `v1.0.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: