[910] minimalistic ref data
mission-apprentissage/labonnealternance pull request #262
Opened 2023-02-27 16:07 UTC by bdavidxyz

2023-03-13 09:00 UTC, alanlr commented on server/src/mocks/userrecruteurs.mock.js
> +;[
le ; sert à quelque chose ?

2023-03-13 09:08 UTC, alanlr approved these changes

2023-03-13 10:47 UTC, kevbarns requested changes
- Existe-il un script pour intégrer ces données seed dans la base de données ? 
- Il manque le type ENTREPRISE & OPCO pour être raccord avec les type d'utilisateurs possible à ce jour
- Conserver l'Id mongo peut poser problème à la creation il me semble, à valider

2023-03-14 14:14 UTC, bdavidxyz commented
- J'avais essayé il semble de scripter tout ceci il y a 15j, mais sans succès
 - Ok pour le type manquant
 - L'ID est supporté à l'import dans MongoDB Compass, mais effectivement il faudrait le supprimer.

On peut fermer cette PR sans merger, je vais me débrouiller sans en attendant.

2023-03-14 14:52 UTC, closed without merging