feat: refacto en service des formulaires + ts + accès direct recherches lbac
mission-apprentissage/labonnealternance pull request #315
Opened 2023-03-22 15:59 UTC by alanlr

2023-03-22 16:02 UTC, alanlr commented on server/src/http/routes/formulaire.controller.ts
> +      // Note pour PR quel traitement de getJobById empêche de l'utiliser ici ?
@kevbarns petite question en commentaire :)

2023-03-28 13:02 UTC, kevbarns requested changes
comme discuter revoir le service en lassant la logique métier dans la route pour le moment

2023-03-28 13:02 UTC, kevbarns commented on server/src/http/routes/formulaire.controller.ts
> +      const response = await createFormulaireWithHotfix(req.body)
pourquoi hotfix ?

2023-03-28 13:02 UTC, kevbarns commented on server/src/common/model/schema/offre/offre.types.ts
> +  supprimer: string
j'ai un doute là, car à l'insertion, ces paramètre n'existe pas dans la collection et ne sont donc pas des paramètre à passer pour créer un enregistrement. Tu dois déclarer des interfaces qui étendent celles-ci localement.

2023-03-28 13:02 UTC, kevbarns commented on server/src/common/model/schema/formulaire/formulaire.types.ts
> +  mailing: object
mailing & events ont été supprimé ou vont l'être. 
entreprise_localité est créé uniquement pour LBA il me semble, même commentaire que pour `offre.types.ts`

2023-03-28 13:05 UTC, kevbarns commented on server/src/common/model/schema/offre/offre.types.ts
> +  supprimer: string
```js
interface IOffreEtendu extends IOffre {
  candidatures: number
  pourvue: string
  supprimer: string
}
```

2023-04-04 14:05 UTC, kevbarns approved these changes
👍

2023-04-19 16:35 UTC, merged

2023-06-02 08:41 UTC, kevbarns commented
:tada: This PR is included in version 1.14.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.14.0)
- `v1.14.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: