feat: use more fields from catalogue
mission-apprentissage/labonnealternance pull request #369
Opened 2023-04-20 09:50 UTC by alanlr

2023-04-25 08:56 UTC, alanlr commented
### A reviewer mais surtout à ne pas merger dans main tant que les données RCO ne sont pas finalisées et disponibles sur leur production

2023-04-25 10:03 UTC, bdavidxyz requested changes

2023-04-25 10:03 UTC, bdavidxyz commented on ui/services/fetchTrainingDetails.js
> +  const isAxiosError = !!_.get(response, "data.error") || !!_.get(lbfResponse, "data.error")
lodash _.get method is now deprecated, you can do like this : 

!!response?.data?.error || !!lbfResponse?.data?.error

2023-06-09 09:12 UTC, merged

2023-06-09 09:12 UTC, kevbarns commented
:tada: This PR is included in version 1.19.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.19.0)
- `v1.19.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: