Feat - MAJ filtre catalogue
mission-apprentissage/labonnealternance pull request #37
Opened 2022-11-15 09:18 UTC by guilletmarion

Si aucun filtre de passé à l'appel du catalogue, récupération par défaut des formations en published = true et catalogue_published = true

2022-11-15 09:34 UTC, kevbarns commented
@alanlr vérifier que le paramètre query n'est pas passé

2022-11-16 09:21 UTC, alanlr commented
Les modifications faites ici sont sur les données déjà importées depuis le catalogue. Ca tape dans notre elasticsearch local. Du coup c'est pas ici qu'il faut faire les modifications. Par contre on peut supprimer les notions de published et catalogue_published car c'est devenu obsolète pour ces appels de code.

C'est au niveau de la fonction fetchFormations de /components/catalogue.js qu'il faut faire les modifs (ligne 70).

2022-11-16 09:23 UTC, alanlr requested changes
Modifier catalogue.js/fetchFormations.
Supprimer publishedMustTerm et son usage de formations.js

2022-11-16 18:41 UTC, merged

2023-03-14 15:25 UTC, kevbarns commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.0.0)
- `v1.0.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: