feat: add base bal api call
mission-apprentissage/labonnealternance pull request #370
Opened 2023-04-20 10:40 UTC by antoinebigard

**Metier**

Ajout de l'appel vers l'api BAL pour vérification de l'appartenance à une organisation. 

https://bal.apprentissage.beta.gouv.fr/api/documentation/static/index.html

**Tech**
- On ne peut pas faire de pr en Draft 🤔  moyen
- Je vous ai ajouté un rate limiter au passage 
 - Caching appels APi externe 
 
 @rimiti @alanlr @kevbarns

2023-04-20 13:17 UTC, alanlr requested changes

2023-04-20 13:17 UTC, alanlr commented on server/package.json
> +    "rate-limiter-flexible": "2.3.6",
on a déjà express-rate-limit. Doit on migrer pour nos usages de limitation des requêtes entrante car rate-limiter-flexible tue le game ? Idéalement il n'en faudrait qu'un qui fasse les deux usages.

2023-04-20 13:17 UTC, alanlr commented on server/src/common/bal.ts
> +      throw new ApiError("Api BAL", `${error.message} for siret=${siret}`, error.code || error.response?.status)
tu voulais faire error = new Api ou un throw ?

2023-04-20 13:17 UTC, alanlr commented on server/src/common/client.ts
> +
Ca vaudrait pas le coup de fusionner le fichier avec apiUtils ?

2023-04-20 13:17 UTC, alanlr commented on server/src/config.ts
> +    apiKey: env.get("LBA_BAL_API_KEY").default("").asString(),
fait moi signe pour qu'on voit comment et qui modifie le vault

2023-04-20 13:17 UTC, alanlr commented on server/src/http/routes/etablissementRecruteur.controller.ts
> +        .validateAsync(req.body, { abortEarly: false });
indentation et ; (plus de ; sur lba)

2023-04-20 13:17 UTC, alanlr commented on server/src/http/utils/validators.ts
> +    .creditCard()
pourquoi le .creditCard pour les siret ? ca fait quoi ? (pas la première fois que je le vois)

2023-04-20 13:17 UTC, alanlr commented on server/src/http/utils/validators.ts
> +          ? `Error: schema not valid : ValidationError: ${error.key} must follow Luhn algorithm`
ah ok réponse à ma question ci-dessus

2023-04-20 13:25 UTC, antoinebigard commented on server/package.json
> +    "rate-limiter-flexible": "2.3.6",
Pas le même usage
la cest les requests sortante

2023-04-20 13:25 UTC, antoinebigard commented on server/src/common/client.ts
> +
à vous de voir ça

2023-04-20 13:26 UTC, antoinebigard commented on server/src/config.ts
> +    apiKey: env.get("LBA_BAL_API_KEY").default("").asString(),
Oui c'est pas encore en prod.

2023-04-20 13:27 UTC, antoinebigard commented on server/src/http/utils/validators.ts
> +    .creditCard()
Algo luhn

2023-04-26 18:48 UTC, merged

2023-06-02 08:40 UTC, kevbarns commented
:tada: This PR is included in version 1.14.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.14.0)
- `v1.14.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: