[699] Motifs RDV
mission-apprentissage/labonnealternance pull request #374
Opened 2023-04-25 07:54 UTC by bdavidxyz

2023-04-25 12:11 UTC, rimiti commented on server/src/common/model/schema/appointments/appointments.types.ts
> +  applicant_reasons: string[]
En réalité, ca serait mieux que ce soit un "enum" avec les valeurs plutot que du string.

2023-04-25 12:13 UTC, rimiti commented on ui_espace_pro/src/pages/Candidat/FormCreatePage.jsx
> +  const checkboxesName = ["modalite", "contenu", "porte", "frais", "place", "horaire", "plus", "accompagnement", "lieu", "suivi", "autre"]
Le mieux serait de créer un dictionnaire du style

```
const reasons = {
MODALITE : "modalite"
}
```

En cas de refacto, ça sera beaucou plus simple.

Ensuite pour le "const checkboxesName", tu pourras simplement faire un Object.values(reasons)

2023-04-25 12:14 UTC, rimiti commented on ui_espace_pro/src/pages/Candidat/FormCreatePage.jsx
> +  const handleOnChange = (checkboxName) => {
jsdoc ? :)

2023-04-25 12:14 UTC, rimiti commented on ui_espace_pro/src/pages/Candidat/FormCreatePage.jsx
> +                    loading={submitLoading.toString()}
```suggestion
                    loading={submitLoading}
```

submitLoading est un boolean

2023-04-25 12:15 UTC, rimiti commented on ui_espace_pro/src/pages/CfaCandidatInformationPage/CfaCandidatInformationPage.jsx
> +  const gimmeAReason = (reason) => {
Ce dict devrait être exporté ailleurs que dans le composant.

2023-04-25 12:15 UTC, rimiti requested changes
Some changes to do.

2023-04-25 12:18 UTC, bdavidxyz commented on ui_espace_pro/src/pages/Candidat/FormCreatePage.jsx
> +  const checkboxesName = ["modalite", "contenu", "porte", "frais", "place", "horaire", "plus", "accompagnement", "lieu", "suivi", "autre"]
Possible que le Object.values ne passe pas la barrière de "Talisman" (j'ai déjà essayé)

2023-04-25 12:19 UTC, bdavidxyz commented on ui_espace_pro/src/pages/Candidat/FormCreatePage.jsx
> +                    loading={submitLoading.toString()}
submitLoading n'est pas supporté en tant que booléen sur la propriété loading

2023-04-25 14:35 UTC, bdavidxyz commented on ui_espace_pro/src/pages/CfaCandidatInformationPage/CfaCandidatInformationPage.jsx
> +  const gimmeAReason = (reason) => {
c'est exporté

2023-04-25 14:37 UTC, bdavidxyz commented on server/src/common/model/schema/appointments/appointments.types.ts
> +  applicant_reasons: string[]
c'est un enum désormais

2023-04-25 14:48 UTC, alanlr requested changes

2023-04-25 14:48 UTC, alanlr commented on server/src/assets/templates/mail-cfa-demande-de-contact.mjml.ejs
> +                                    <% if (reason == 'modalite') { %>
un switch case serait plus approprié

2023-04-25 14:48 UTC, alanlr commented on server/src/common/model/schema/appointments/appointment.schema.ts
> +    type: "array",
type: [String] (ou autre chose que string selon le type de applicant_reason)

2023-04-25 14:48 UTC, alanlr commented on ui_espace_pro/src/common/utils/reasonsUtils.js
> +  modalite: "Modalités d'inscription",
clef de constante en majuscules et à mettre en export dans le fichier constants.ts.

2023-04-25 14:48 UTC, alanlr commented on server/src/common/model/schema/appointments/appointments.types.ts
> +  applicant_reasons: EReasons[]
suis pas assez qualifié pour être sûr de la syntaxe ici ;-)

2023-04-25 14:48 UTC, alanlr commented on ui_espace_pro/src/common/utils/reasonsUtils.js
> +export const gimmeAReason = (reason) => {
getReasonText plus parlant sur le long terme ;-)

2023-04-25 14:48 UTC, alanlr commented on ui_espace_pro/src/common/utils/reasonsUtils.js
> +export const getReasons = () => {
getAllReasonKeys ?

2023-04-25 14:48 UTC, alanlr commented on ui_espace_pro/src/pages/Candidat/FormCreatePage.jsx
> +          invalid: "true",
pour quelle raison une string plutôt qu'un booléen ?

2023-04-25 14:48 UTC, alanlr commented on ui_espace_pro/src/pages/Candidat/FormCreatePage.jsx
> +                        return <Input placeholder="période d’inscription, horaires, etc." {...field} {...feedback(meta, "Désolée, ce champs est nécessaire")} />
"Désolé"

2023-04-25 14:51 UTC, bdavidxyz commented on ui_espace_pro/src/pages/Candidat/FormCreatePage.jsx
> +          invalid: "true",
sinon ça bug

2023-04-25 14:58 UTC, bdavidxyz commented on ui_espace_pro/src/common/utils/reasonsUtils.js
> +export const getReasons = () => {
je garde getReasons qui est plus simple et plus cohérent avec le reste du code (notamment backend)

2023-04-25 14:59 UTC, bdavidxyz commented on server/src/assets/templates/mail-cfa-demande-de-contact.mjml.ejs
> +                                    <% if (reason == 'modalite') { %>
on garde le else/if qui est plus sûr et plus lisible (le switch case est théoriquement possible, mais assez illisible dans un template)

2023-04-25 15:01 UTC, bdavidxyz commented on ui_espace_pro/src/common/utils/reasonsUtils.js
> +  modalite: "Modalités d'inscription",
non car j'ai besoin des clés telles quelles dans le code. En rajouter me ferais faire une petite couche d'over engineering...

2023-04-25 15:14 UTC, bdavidxyz commented on server/src/common/model/schema/appointments/appointment.schema.ts
> +    type: "array",
non, ça doit être déclaré comme "array"

2023-04-25 15:16 UTC, alanlr approved these changes

2023-04-25 16:53 UTC, merged

2023-06-02 08:41 UTC, kevbarns commented
:tada: This PR is included in version 1.14.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.14.0)
- `v1.14.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: