feat: script setFormateurSiretOnAppointments created
mission-apprentissage/labonnealternance pull request #383
Opened 2023-05-03 15:08 UTC by rimiti

## PURPOSE

Jira: https://mna-matcha.atlassian.net/browse/LBAC-1160

2023-05-03 16:24 UTC, kevbarns requested changes
🚀 || garder le `cli.ts` pour les job récurrents

2023-05-03 16:24 UTC, kevbarns commented on server/src/cli.ts
> +import { setFormateurSiretOnAppointments } from "./jobs/rdv/oneTimeJob/setFormateurSiretOnAppointments.js"
c'est un script récurent ? si c'est un "one-shot" autant ne pas mettre de CLI et l'executer à la main sur le docker.

2023-05-04 07:05 UTC, rimiti commented on server/src/cli.ts
> +import { setFormateurSiretOnAppointments } from "./jobs/rdv/oneTimeJob/setFormateurSiretOnAppointments.js"
Je pense qu'il va être de nouveau utile pour de prochains champs, c'est pour cette raison que je l'ai mis dans le cli.

2023-05-09 14:14 UTC, rimiti commented on server/src/cli.ts
> +import { setFormateurSiretOnAppointments } from "./jobs/rdv/oneTimeJob/setFormateurSiretOnAppointments.js"
J'ai tout de même drop pour accélérer la review ;)

2023-05-09 14:18 UTC, alanlr approved these changes

2023-05-09 14:26 UTC, kevbarns approved these changes

2023-05-09 14:26 UTC, kevbarns commented on server/src/cli.ts
> +import { setFormateurSiretOnAppointments } from "./jobs/rdv/oneTimeJob/setFormateurSiretOnAppointments.js"
Ambiguë cet usage, retire le c'est préférable.

2023-05-09 14:35 UTC, merged

2023-06-02 08:40 UTC, kevbarns commented
:tada: This PR is included in version 1.14.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.14.0)
- `v1.14.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: