Feat: 1023 - Désinscription entreprise
mission-apprentissage/labonnealternance pull request #397
Opened 2023-05-17 12:32 UTC by guilletmarion

2023-05-17 12:33 UTC, guilletmarion commented
On reçoit toujours des demandes de désinscription côté support avec l'objet "Désinscription entreprise - Candidature en ligne".
En analysant le code, j'ai vu qu'on avait toujours ce lien. Je le supprime

2023-05-17 16:18 UTC, alanlr requested changes

2023-05-17 16:18 UTC, alanlr commented on ui/components/DesinscriptionEntreprise/FormulaireDesinscription.js
> +  AUTRE: "Autre",
Il faut que tu ajoutes aussi AUTRE: "Autre", dans le fichier constants.ts

2023-05-17 17:17 UTC, alanlr approved these changes

2023-05-22 13:53 UTC, merged

2023-06-02 08:40 UTC, kevbarns commented
:tada: This PR is included in version 1.14.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.14.0)
- `v1.14.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: