feat: migration service application -> services  application.services
mission-apprentissage/labonnealternance pull request #398
Opened 2023-05-17 14:58 UTC by alanlr

2023-06-08 13:45 UTC, kevbarns commented on server/src/services/mailer.service.ts
> +export const mailer = await createMailer()
Service à migrer rapidement pour retirer la rustine

2023-06-08 13:56 UTC, kevbarns requested changes
👍

2023-06-08 13:56 UTC, kevbarns commented on server/src/services/application.service.ts
> +  }
Utiliser Joi (on supprime Yup du back) et tu peux chainer l'objet avec un validate : 

```js
const {value, error} = Joi.object({...}).validate()

if(error){...}
```

2023-06-08 13:56 UTC, kevbarns commented on server/src/services/application.service.ts
> +  }
cette partie (Yup) peut se faire directement sur le front et être supprimé du back pour un feedback immédiat et éviter le transfert du fichier sur le server.

2023-06-08 13:56 UTC, kevbarns commented on server/src/services/application.service.ts
> +}
idem, utiliser Joi ou déporter sur le Front pour laisser feedback immédiat et ne pas solliciter le back

2023-06-08 13:56 UTC, kevbarns commented on server/src/services/application.service.ts
> +}
idem que les autres remarque sur Yup/Joi et déporté côté Front.

2023-06-08 13:56 UTC, kevbarns commented on server/src/services/application.service.ts
> +}
idem que les autres remarque sur Yup/Joi et déporté côté Front.

2023-06-09 09:27 UTC, alanlr commented on server/src/services/application.service.ts
> +  }
Le service peut être appelé par api externe (diagoriente notamment) . On a déjà les ctrls côté client pour notre ui.

2023-06-14 10:09 UTC, kevbarns approved these changes
👍

2023-06-14 11:14 UTC, merged

2023-06-14 11:15 UTC, kevbarns commented
:tada: This PR is included in version 1.22.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.22.0)
- `v1.22.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: