feat: génération des liens vers LBA et prdv en fonction des voeux
mission-apprentissage/labonnealternance pull request #406
Opened 2023-05-30 09:27 UTC by alanlr

2023-05-31 09:42 UTC, rimiti commented on server/src/http/routes/trainingLinks.controller.ts
> +        return await EligibleTrainingsForAppointment.findOne({cle_ministere_educatif:training.cle_ministere_educatif}) ? `https://labonnealternance.apprentissage.beta.gouv.fr/espace-pro/form?referrer
```suggestion
        return EligibleTrainingsForAppointment.findOne({cle_ministere_educatif:training.cle_ministere_educatif}) ? `https://labonnealternance.apprentissage.beta.gouv.fr/espace-pro/form?referrer=lba&cleMinistereEducatif=${encodeURIComponent(training.cle_ministere_educatif)}`:""
```

await pas necessaire quand tu return.

2023-05-31 09:43 UTC, rimiti commented on server/src/http/routes/trainingLinks.controller.ts
> +        return `https://labonnealternance.apprentissage.beta.gouv.fr/recherche-emploi?&romes=${romes}${lat && lon ? `&lat=${lat}&lon=${lon}&radius=60`:""}`
A mon avis, il serait mieux d'utiliser l'Object new URL de node.

2023-05-31 09:44 UTC, rimiti commented on server/src/http/routes/trainingLinks.controller.ts
> +                    result.lien_lba = await getLBALink(training)
Tu peux utiliser un Promise.all ici. :)

2023-05-31 09:46 UTC, alanlr commented on server/src/http/routes/trainingLinks.controller.ts
> +                    result.lien_lba = await getLBALink(training)
ok je vais faire ça

2023-05-31 11:33 UTC, alanlr commented on server/src/http/routes/trainingLinks.controller.ts
> +        return `https://labonnealternance.apprentissage.beta.gouv.fr/recherche-emploi?&romes=${romes}${lat && lon ? `&lat=${lat}&lon=${lon}&radius=60`:""}`
Done

2023-05-31 13:57 UTC, kevbarns requested changes
Tu peux déclarer une URL de base et rajouter des paramètres dans lorsque tes conditions sont remplies :

```js
const lbaLink = new URL("https://labonnealternance.apprentissage.beta.gouv.fr/recherche-emploi")

lbaLink.search = "romes=<ROME>&lat=<LAT>&etc..."

```

2023-05-31 13:57 UTC, kevbarns commented on server/src/http/routes/trainingLinks.controller.ts
> +        }
Mettre un schéma de validation ici

2023-05-31 13:57 UTC, kevbarns commented on server/src/http/routes/trainingLinks.controller.ts
> +const getPrdvLink = async (training: Partial<ITraining>): Promise<string> => {
Pourquoi avoir déclaré un nouveau type plutôt que d'utiliser celui de la collection en Partial ? ou utiliser un Pick

2023-05-31 15:30 UTC, alanlr commented on server/src/http/routes/trainingLinks.controller.ts
> +const getPrdvLink = async (training: Partial<ITraining>): Promise<string> => {
C'est pas corrélé à la collection

2023-05-31 20:20 UTC, kevbarns commented on server/src/http/routes/trainingLinks.controller.ts
> +const getPrdvLink = async (training: Partial<ITraining>): Promise<string> => {
Les types correspondent pas à ce que tu reçois ?

2023-05-31 20:21 UTC, kevbarns commented on server/src/http/routes/trainingLinks.controller.ts
> +        }
Placer le code dans un services également pour arranger le code 👍

2023-06-01 15:03 UTC, alanlr commented on server/src/services/trainingLinks.service.ts
> +    const elligibleFormation = await EligibleTrainingsForAppointment.findOne({ cle_ministere_educatif: training.cle_ministere_educatif }, { _id: 1 })
Le countDocuments ici s'est avéré une fausse bonne idée. Ca multipliait le temps de réponse par 4. Je me suis permis d'ajouter un index sur le champ cle_ministere_educatif dans la collection ElligibleTrainingsForAppointments.

2023-06-02 07:44 UTC, kevbarns approved these changes

2023-06-07 10:23 UTC, rimiti approved these changes

2023-06-08 07:15 UTC, merged

2023-06-08 07:16 UTC, kevbarns commented
:tada: This PR is included in version 1.17.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.17.0)
- `v1.17.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: