feat: move service formations
mission-apprentissage/labonnealternance pull request #451
Opened 2023-06-21 13:24 UTC by alanlr

2023-06-21 15:10 UTC, kevbarns requested changes

2023-06-21 15:10 UTC, kevbarns commented on server/src/http/controllers/metiers/metiers.controller.ts
> +import { TResponseError } from "../shared.controllers.types.js"
Gardons l'extension controller(s) pour les routes. Point d'attention, cette extention `controller` est lu par TSOA, seul les routes peuvent le porter. (voir config)

2023-06-21 15:10 UTC, kevbarns commented on server/src/services/formation.service.ts
> +const lbfDescriptionUrl = "https://labonneformation.pole-emploi.fr/api/v1/detail"
à placer dans `config.ts` et utiliser directement `config.lbfApiUrl` sans le pathname (detail)

2023-06-21 15:10 UTC, kevbarns commented on server/src/services/formation.service.ts
> +  }
```suggestion
    return value ? diplomaMap[value[0]] : ""
```

2023-06-21 15:10 UTC, kevbarns commented on server/src/services/formation.service.ts
> +    const distance = radius || 30
```suggestion
    const distance = radius ?? 30
```

préférer ?? au lieu de || pour setter une valeur. https://github.com/tc39/proposal-nullish-coalescing#overview-and-motivation

2023-06-21 15:10 UTC, kevbarns commented on server/src/services/formation.service.ts
> +    const tags: number[] = [now.getFullYear(), now.getFullYear() + 1, now.getFullYear() + (now.getMonth() < 8 ? -1 : 2)]
```suggestion
    const now = new Date()
    const tags = [now.getFullYear(), now.getFullYear() + 1, now.getFullYear() + (now.getMonth() < 8 ? -1 : 2)]
```

Préférer l'inférence TS pour les variables si ce sont pas des objets/arrays complexes pour lesquels le type n'a pas été passé par l'origine

2023-06-21 15:10 UTC, kevbarns commented on server/src/services/formation.service.ts
> +    const mustTerm: object[] = [
👍

2023-06-21 15:10 UTC, kevbarns commented on server/src/services/formation.service.ts
> +  const formations: ILbaItem[] = transformFormationsForIdea(rawEsFormations)
```suggestion
  const formations = transformFormationsForIdea(rawEsFormations)
```
la fonction parent renvoie bien le type, laisser l'inférence typer la variable

2023-06-21 15:10 UTC, kevbarns commented on server/src/services/formation.service.ts
> +    data.sessions.forEach((session, idx) => {
C'est normal que session ne soit pas utiliser ? si oui tu peux placer un _

2023-06-21 15:10 UTC, kevbarns commented on server/src/services/formation.service.ts
> + * @returns {Promise< IApiError | ILbaItem[] >}
Attention sur VS code je vois qu'ici :
```js
| ILbaItem[]
```
ce n'est pas un espace entre le pipe et le I de ILbaItem[]
<img width="390" alt="Capture d’écran 2023-06-21 à 17 06 05" src="https://github.com/mission-apprentissage/labonnealternance/assets/22106329/b80e55d5-c1be-4298-8855-a2563d036ef0">

2023-06-21 15:10 UTC, kevbarns commented on server/src/services/formation.service.ts
> +    const formations: ILbaItem[] = transformFormationsForIdea(rawEsFormations)
```suggestion
    const formations = transformFormationsForIdea(rawEsFormations)
```

2023-06-21 15:10 UTC, kevbarns commented on server/src/services/shared.service.types.ts
je sens qu'on va y mettre plein de chose ici si on démarre un `shared.service.types.ts`. Trouvons un nom que s'accorde avec les objets métiers.

2023-06-21 16:11 UTC, alanlr commented on server/src/http/controllers/metiers/metiers.controller.ts
> +import { TResponseError } from "../shared.controllers.types.js"
ok. juste un point d'attention sur le fait que le shared.types.ts est déjà présent par ailleurs dans les modèles.

2023-06-21 16:27 UTC, alanlr commented on server/src/services/formation.service.ts
> +    const distance = radius || 30
ok mais je vais d'abord m'assurer que le radius n'est pas parfois initialisé à 0 ou "" par erreur.

2023-06-21 16:33 UTC, alanlr commented on server/src/services/formation.service.ts
> +    const distance = radius || 30
bon en l'état radius est autorisé à 0 mais pas à "".  Or si quelqu'un mets 0 dans le call ou le remplace par 30 pour les formations pour forcer des résultats. (décision métier) L'illusion de la recherche en lieu exact.

2023-06-21 16:36 UTC, kevbarns commented on server/src/services/formation.service.ts
> +    const distance = radius || 30
ok, faudrait typer le radius en number et passer 0 ou null pour 0 pour éviter le "" dans une intégration avec Joi

2023-06-22 08:20 UTC, kevbarns approved these changes

2023-06-22 13:10 UTC, merged

2023-06-22 13:11 UTC, kevbarns commented
:tada: This PR is included in version 1.37.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.37.0)
- `v1.37.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: