feat: move sendinblue service to brevo services
mission-apprentissage/labonnealternance pull request #452
Opened 2023-06-21 14:15 UTC by alanlr

- déplacement des éléments de service autour de sendinblue dans le dossier /services
- renommage de sendinblue en brevo

2023-06-21 14:31 UTC, kevbarns requested changes

2023-06-21 14:31 UTC, kevbarns commented on server/src/cli.ts
>    .description("Récupère auprès de Sendinblue la liste des adresses emails bloquées le jour précédent (défaut) ou toutes les adresses bloquées (option)")
```suggestion
  .description("Récupère auprès de Brevo la liste des adresses emails bloquées le jour précédent (défaut) ou toutes les adresses bloquées (option)")
```

2023-06-21 14:31 UTC, kevbarns commented on server/src/config.ts
> +    brevoWebhookApiAccessCode: env.get("LBA_SENDINBLUE_WEBHOOK_API_KEY").default("1234").asString(),
```suggestion
    brevoWebhookApiAccessCode: env.get("LBA_BREVO_WEBHOOK_API_KEY").default("1234").asString(),
```

Prévoir update côté infra + 1P

2023-06-21 14:31 UTC, kevbarns commented on server/src/config.ts
> +    brevoApiAccessCode: env.get("LBA_SENDINBLUE_API_KEY").default("1234").asString(),
```suggestion
    brevoApiAccessCode: env.get("LBA_BREVO_API_KEY").default("1234").asString(),
```

2023-06-21 15:08 UTC, alanlr commented on server/src/config.ts
> +    brevoWebhookApiAccessCode: env.get("LBA_SENDINBLUE_WEBHOOK_API_KEY").default("1234").asString(),
oui. tu fais bien de rappeler le 1P.

2023-06-22 07:12 UTC, kevbarns approved these changes

2023-06-27 08:45 UTC, merged

2023-06-27 08:46 UTC, kevbarns commented
:tada: This PR is included in version 1.42.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.42.0)
- `v1.42.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: