feat(OF): permet aux OF de se désinscrire des mises en relation
mission-apprentissage/labonnealternance pull request #495
Opened 2023-07-06 14:27 UTC by remy-auricoste

![image](https://github.com/mission-apprentissage/labonnealternance/assets/5033491/c3c79462-fc53-4b5c-b12e-c63facf654ce)

2023-07-06 15:39 UTC, kevbarns requested changes
- Remettre les extensions .js, on va s'occuper de la config TS dans une branche dédié et modifier tous le code en conséquence
- Uniquement modifier le code en relation avec la feature/fix, plutôt que d'effectuer des fix/optimisation ici et là, proposer les optimisations dans une branche dédié.

2023-07-06 15:39 UTC, kevbarns commented on server/src/services/etablissement.service.ts
> +}
```suggestion
export const unsuscribeEstablishmentFromDelegationRequests = async (etablissementSiret: string) => UnsubscribeOF..findByIdAndUpdate(
      { establishment_siret:etablissementSiret },
      {
        establishment_siret: etablissementSiret,
        unsubscribe_date: new Date(),
      },
      { upsert: true }
    )
```

2023-07-06 15:39 UTC, kevbarns commented on server/src/common/model/schema/unsubscribedOF/unsubscribeOF.types.ts
> +  siret: string
```suggestion
  establishment_siret: string
```

2023-07-06 15:39 UTC, kevbarns commented on server/src/common/model/schema/unsubscribedOF/unsubscribeOF.schema.ts
> +  siret: {
```suggestion
  establishment_siret: {
```

2023-07-06 15:39 UTC, kevbarns commented on server/src/common/model/schema/unsubscribedOF/unsubscribeOF.schema.ts
> +    description: "Le Siret de la société",
```suggestion
    description: "Le Siret de l'organisme de formation",
```

2023-07-06 15:39 UTC, kevbarns commented on server/src/common/model/schema/unsubscribedOF/unsubscribeOF.schema.ts
> +    default: Date.now,
Stocker la date au format ZULU ou ISO.

A vérifier que cette date là ne soit pas définit au démarrage du server, au lieu de prendre la date de la creation de l'enregistrement

2023-07-06 15:39 UTC, kevbarns commented on server/src/http/routes/user.controller.ts
> +import { createUser, updateUser, updateUserValidationHistory, removeUser } from "../../services/userRecruteur.service.ts"
Effectuer uniquement les modifications qui concerne la features. Ici remplacer les .js par .ts va plus causer un problème.

On va corriger ça sur l'ensemble des fichier, pas seulement ici et là et modifier la tsconfig en conséquence

2023-07-06 15:39 UTC, kevbarns commented on server/src/services/etablissement.service.ts
> +}
+ ajouter JSDOC

2023-07-06 15:39 UTC, kevbarns commented on server/src/services/formulaire.service.ts
> +export const sendCFADelegationMail = async (email: string, offre: IJobs, recruiter: { establishment_raison_sociale: string; establishment_id: string }, siret_code: string) => {
💯

2023-07-06 15:39 UTC, kevbarns commented on ui_espace_pro/src/pages/Proposition/Offre/PropositionOffreUnsubscribe.jsx
> +  })
Ajouter une fonction dédié dans `ui_espace_pro/src/api.js`

2023-07-06 15:40 UTC, kevbarns commented on server/src/services/etablissement.service.ts
> +}
faute à ~~unsuscribe~~ -> unsubscribe

2023-07-07 14:27 UTC, remy-auricoste commented on server/src/http/routes/user.controller.ts
> +import { createUser, updateUser, updateUserValidationHistory, removeUser } from "../../services/userRecruteur.service.ts"
je vais éviter de corriger au fur et a mesure alors. C'est juste que ça me gonfle de voir du rouge partout dans les fichiers

2023-07-07 14:30 UTC, remy-auricoste commented on server/src/services/etablissement.service.ts
> +}
je pense qu'on veut garder l'ancienne date si l'utilisateur reclicke. D'où l'insert et pas d'update

2023-07-07 14:38 UTC, remy-auricoste commented on server/src/common/model/schema/unsubscribedOF/unsubscribeOF.schema.ts
> +    default: Date.now,
j'ai supprimé la valeur par défaut puisqu'elle est écrite par le service. Si le type n'est pas bon, quel type je dois utiliser ? string ?

2023-07-07 14:46 UTC, remy-auricoste commented
> * Remettre les extensions `.js`, on va s'occuper de la config TS dans une branche dédié et modifier tous le code en conséquence --> le build fail
> * Uniquement modifier le code en relation avec la feature/fix, plutôt que d'effectuer des fix/optimisation ici et là, proposer les optimisations dans une branche dédié.
=> je suis plutôt adepte de la [boy scout rule](https://deviq.com/principles/boy-scout-rule). Si ça casse le build, je vais bien sûr revert les changements. Mais dans la mesure du possible, je préfère améliorer le code petit à petit. Je trouve ça moins chronophage et plus gratifiant.

2023-07-07 15:32 UTC, remy-auricoste commented on ui_espace_pro/src/pages/Proposition/Offre/PropositionOffreUnsubscribe.jsx
> +  })
done

2023-07-10 12:32 UTC, remy-auricoste commented on server/src/services/etablissement.service.ts
> +}
j'ai ajouté la JsDoc

2023-07-10 12:52 UTC, kevbarns commented on server/src/common/model/schema/unsubscribedOF/unsubscribeOF.schema.ts
> +    default: Date.now,
Date c'est bien 👍

2023-07-10 12:52 UTC, kevbarns approved these changes
👍

2023-07-10 14:17 UTC, kevbarns commented on server/src/http/routes/etablissementRecruteur.controller.ts
> +      }
A placer dans le service directement selon moi

2023-07-12 07:54 UTC, remy-auricoste commented on server/src/http/routes/etablissementRecruteur.controller.ts
> +      }
done

2023-07-12 08:34 UTC, merged

2023-07-12 08:34 UTC, kevbarns commented
:tada: This PR is included in version 1.51.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.51.0)
- `v1.51.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: