Feat: LBAC-1079 and LBAC-1078
mission-apprentissage/labonnealternance pull request #533
Opened 2023-08-08 10:44 UTC by rimiti

+ feat: Invitation Parcoursup sur une période donnée
+ feat: Invitation Affelnet sur une période donnée 
+ refactor: remove components from rdv jobs to directly use services
+ chore: improve typing

2023-08-08 13:04 UTC, alanlr requested changes

2023-08-08 13:04 UTC, alanlr commented on server/src/jobs/rdv/inviteEtablissementToPremiumAffelnet.ts
> +  if (!dayjs().isBetween(startInvitationPeriod, endInvitationPeriod)) {
isBetween semble exclure les dates bornes par défaut.

2023-08-08 13:04 UTC, alanlr commented on server/src/jobs/rdv/inviteEtablissementToPremium.ts
> +  if (!dayjs().isBetween(startInvitationPeriod, endInvitationPeriod)) {
attention isBetween semblent exclure les dates bornes par défaut

2023-08-08 13:22 UTC, rimiti commented on server/src/jobs/rdv/inviteEtablissementToPremiumAffelnet.ts
> +  if (!dayjs().isBetween(startInvitationPeriod, endInvitationPeriod)) {
Bien vu !

2023-08-08 13:31 UTC, alanlr approved these changes

2023-08-08 13:32 UTC, merged

2023-08-09 07:16 UTC, kevbarns commented
:tada: This PR is included in version 1.68.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.68.0)
- `v1.68.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: