Feat lbac 1390 training link enhancement
mission-apprentissage/labonnealternance pull request #542
Opened 2023-08-17 16:30 UTC by kevbarns

- add new parameters accepted by the API
- update fetching logic + refactoring

2023-08-18 07:04 UTC, remy-auricoste commented on server/src/services/trainingLinks.service.ts
> +const lbaCandidat = new URL(`${lbaDomain}/recherche-emploi`)
ca fonctionne actuellement mais c'est pas thread safe. Ca peut amener des bugs de race condition si on utilise des promises plus tard.
```suggestion
const lbaCandidat = () => new URL(`${lbaDomain}/recherche-emploi`)
```

2023-08-18 07:04 UTC, remy-auricoste commented on server/src/services/trainingLinks.service.ts
> +const lbaCandidat = new URL(`${lbaDomain}/recherche-emploi`)
il faut modifier les caller en conséquence

2023-08-18 07:04 UTC, remy-auricoste commented on server/src/services/trainingLinks.service.ts
> +  query: object,
la doc ne correspond pas au typage. De manière générale, il vaut mieux éviter le type `object` si on peut

2023-08-18 07:04 UTC, remy-auricoste commented on server/src/services/trainingLinks.service.ts
> +      romes = Array.from(new Set(formation.map(({ rome_codes }) => rome_codes).flat()))
```suggestion
      romes = [...new Set(formation.flatMap(({ rome_codes }) => rome_codes))]
```

2023-08-18 07:12 UTC, remy-auricoste commented on server/src/services/trainingLinks.service.ts
> +const lbaCandidat = new URL(`${lbaDomain}/recherche-emploi`)
encore mieux :
```suggestion
const buildEmploiUrl = (params: Record<string, string>) => {
  const url = new URL(`${lbaDomain}/recherche-emploi`)
  Object.entries(params).forEach(([key, value]) => url.searchParams.append(key, value))
  return url.toString()
}
```

2023-08-21 07:43 UTC, alanlr commented on server/src/http/routes/trainingLinks.controller.ts
> +            rncp: Joi.when("cfd", { not: Joi.exist(), then: Joi.string().required() }),
On ne peut pas chainer un deuxième .or sur cfd / rncp ?

2023-08-21 07:51 UTC, kevbarns commented on server/src/http/routes/trainingLinks.controller.ts
> +            rncp: Joi.when("cfd", { not: Joi.exist(), then: Joi.string().required() }),
si ça fonctionne 👍

2023-08-23 08:08 UTC, remy-auricoste requested changes

2023-08-23 08:08 UTC, remy-auricoste commented on server/src/services/trainingLinks.service.ts
> +    params: { referrer: "lba", cleMinistereEducatif: encodeURIComponent(wish.cle_ministere_educatif), ...utmData },
```suggestion
    params: { referrer: "lba", cleMinistereEducatif: wish.cle_ministere_educatif, ...utmData },
```
`url.searchParams.append(key, value)` dans `buildEmploiUrl` encode déjà les caractères spéciaux

2023-08-25 08:20 UTC, remy-auricoste approved these changes

2023-09-15 08:23 UTC, merged

2023-09-15 08:34 UTC, kevbarns commented
:tada: This PR is included in version 1.89.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.89.0)
- `v1.89.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: