chore: dead code removed
mission-apprentissage/labonnealternance pull request #596
Opened 2023-09-20 16:03 UTC by rimiti

## Objectif

+ controllers inutilisés supprimés.
+ code mort back supprimé.
+ code mort ui_espace_pro supprimé.

Il faudrait refaire une passe dans les /jobs pour ne garder que ce qui est utile @kevbarns @alanlr.

2023-09-20 16:11 UTC, alanlr requested changes

2023-09-20 16:11 UTC, alanlr commented on server/src/http/server.ts
> -import updateLbaCompany from "./routes/updateLbaCompany.controller"
ca ne doit pas être supprimé

2023-09-20 16:11 UTC, alanlr commented on server/src/http/server.ts
> -  app.use("/api/updateLBB", limiter1Per20Second, updateLbaCompany())
idem

2023-09-21 07:21 UTC, kevbarns commented
⚠️ Attention, il y a des fichier supprimé qui ont été commenté dans le code volontairement pour revenir dessus (ex: corsMiddleware).

2023-09-25 21:13 UTC, closed without merging