Models candidat recruteurs
mission-apprentissage/labonnealternance pull request #597
Opened 2023-09-20 16:23 UTC by remy-auricoste

2023-09-21 13:28 UTC, kevbarns commented on shared/models/job.model.ts
> +    job_status: z.enum([allJobStatus[0], ...allJobStatus.slice(1)]).describe("Statut de l'offre"),
👍

2023-09-22 09:43 UTC, kevbarns commented on shared/routes/rome.routes.ts
> +      queryParams: null, // basic auth
c'est queryString ici d'après `shared/index.ts`

2023-09-22 10:12 UTC, alanlr requested changes

2023-09-22 10:12 UTC, alanlr commented on shared/models/lbaItem.model.ts
> +    .object({
je vais prendre la suite là dessus sur mes prochaines PR et je ferai du découpage en sous morceaux

2023-09-22 10:12 UTC, alanlr commented on shared/routes/v1Jobs.routes.ts
> +        "2xx": ZRecruiter,
utiliser les valeurs réellement renvoyées autant que possible. Ex :  200 ou 201

2023-09-22 10:12 UTC, alanlr commented on shared/routes/v1Jobs.routes.ts
> +      }),
doit y avoir un body aussi ?

2023-09-22 10:12 UTC, alanlr commented on shared/routes/v1Jobs.routes.ts
> +          lbbCompanies: z.null(), // always null ???
à supprimer dans une V2 du contrat d'api ;-)

2023-09-22 11:46 UTC, kevbarns commented on shared/routes/v1Jobs.routes.ts
> +      }),
ajouter .strict() à z.object()

2023-09-22 11:46 UTC, kevbarns commented on shared/routes/v1Jobs.routes.ts
> +    "/api/v1/jobs/:jobId": {
y'a pas de body ici ?

2023-09-22 12:07 UTC, kevbarns commented on shared/routes/v1Jobs.routes.ts
> +      }),
.strict() ici aussi

2023-09-22 12:08 UTC, kevbarns reviewed
- ajouter .strict() au object attendu en body
- queryString au lieu de queryParams

2023-09-22 13:49 UTC, alanlr approved these changes

2023-09-22 13:55 UTC, merged