feat: add session on espace pro [GEN-87]
mission-apprentissage/labonnealternance pull request #625
Opened 2023-10-05 04:14 UTC by antoinebigard

2023-10-05 09:08 UTC, kevbarns reviewed
💯 
Première review, j'ai noté pas mal de call API a déplacer dans un fichier common type `api.ts`

2023-10-05 09:08 UTC, kevbarns commented on server/src/config.ts
> +        secure: env.get("LBA_AUTH_SESSION_COOKIE_SECURE").default("true").asBool(),
Comme le reste de la config, passer tous les paramètres à `required()` force à les avoir dans tous les env dans le vault, ça apport plus de cohérence.

2023-10-05 09:08 UTC, kevbarns commented on server/src/common/model/schema/session/session.schema.ts
> +    },
Pourquoi ne pas utiliser le timestamp mongoose ? `timestamp: true`

2023-10-05 09:08 UTC, kevbarns commented on server/src/services/sessions.service.ts
> +  return Session.findOne(filter, options)
ajouter `.lean()`

2023-10-05 09:08 UTC, kevbarns commented on server/src/services/sessions.service.ts
> +  return Session.updateOne({ _id }, { $set: { ...data, updated_at: new Date() } })
ajouter `.lean()`

2023-10-05 09:08 UTC, kevbarns commented on shared/models/usersRecruteur.model.ts
> +    status_current: getUserStatus(user.status),
L'historique des statuts est visible côté user ADMIN et OPCO, il faut que le tableau `status` remonte ici

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/admin/eligible-trainings-for-appointment/edit/[id].tsx
> +  const getEligibleTrainingsForAppointments = (id) => apiGet("/admin/eligible-trainings-for-appointment/etablissement-formateur-siret/:siret", { params: { siret: id } })
note : appel à déplacer dans fichier global `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/admin/eligible-trainings-for-appointment/edit/[id].tsx
> +  const getEtablissement = (siret) => apiGet("/admin/etablissements/siret-formateur/:siret", { params: { siret: siret } })
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/admin/eligible-trainings-for-appointment/edit/[id].tsx
> +    await apiPatch("/admin/eligible-trainings-for-appointment/:id", { params: { id }, body })
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/admin/eligible-trainings-for-appointment/search.tsx
> +      const formations = (await apiGet("/admin/formations", { querystring: { search_item: keywordEncoded } })) as IFormationCatalogue[]
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/admin/index.tsx
> +      const { appointments } = await apiGet(`/admin/appointments/details`, {})
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/admin/utilisateurs/[userId]/index.tsx
> +      const user = await apiGet("/admin/users/:userId", { params })
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/administration/entreprise/[establishment_id]/edition.tsx
> +  const cfaMutation = useMutation(({ establishment_id, values }) => apiPut(`/formulaire/:establishment_id`, { params: { establishment_id }, body: values }), {
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/administration/index.tsx
> +    apiGet("/etablissement/cfa/:userRecruteurId/entreprises", {
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/administration/opco/entreprise/[siret_userId]/index.tsx
> +  const { data, isLoading } = useQuery("user", () => apiGet(`/user/:userId`, { params: { userId: siret_userId } }), { cacheTime: 0 })
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/administration/users/[userId].tsx
> +  const { data, isLoading }: { data: any; isLoading: boolean } = useQuery("user", () => apiGet(`/user/:userId`, { params: { userId } }), { cacheTime: 0 })
idem à déplacer dans `api.js` - pourquoi ne pas avoir modifier api.ts directement ?

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/creation/fin.tsx
> +  const { isFetched } = useQuery("userdetail", () => apiGet("/user/status/:userId", { params: { userId } }), {
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/establishment/[establishmentId]/appointments/[appointmentId].tsx
> +      await apiPost("/appointment-request/reply", {
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/establishment/[establishmentId]/appointments/[appointmentId].tsx
> +    await apiPost("/appointment-request/reply", {
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/establishment/[establishmentId]/appointments/[appointmentId].tsx
> +    await apiPost("/appointment-request/reply", {
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/establishment/[establishmentId]/appointments/[appointmentId].tsx
> +          await apiPatch("/etablissements/:id/appointments/:appointmentId", { params: { id: establishmentId, appointmentId }, body: { has_been_read: true } })
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/form/confirm/[id].tsx
> +        const response = await apiGet("/appointment-request/context/recap", {
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/form/index.tsx
> +        const response = (await apiPost("/appointment-request/context/create", {
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/form/opt-out/unsubscribe/[id].tsx
> +    await apiPost("/etablissements/:id/opt-out/unsubscribe", {
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/form/opt-out/unsubscribe/[id].tsx
> +      const etablissement = (await apiGet("/etablissements/:id", {
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/form/premium/[id].tsx
> +    await apiPost("/etablissements/:id/premium/accept", {
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/form/premium/[id].tsx
> +    await apiPost("/etablissements/:id/premium/refuse", {
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/form/premium/[id].tsx
> +      const etablissement = (await apiGet("/etablissements/:id", {
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/form/premium/affelnet/[id].tsx
> +    await apiPost("/etablissements/:id/premium/affelnet/accept", {
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/form/premium/affelnet/[id].tsx
> +    await apiPost("/etablissements/:id/premium/affelnet/refuse", {
idem à déplacer dans `api.js`

2023-10-05 09:08 UTC, kevbarns commented on ui/pages/espace-pro/form/premium/affelnet/[id].tsx
> +      const etablissement = (await apiGet("/etablissements/:id", {
idem à déplacer dans `api.js`

2023-10-05 12:25 UTC, antoinebigard commented on ui/pages/espace-pro/form/premium/[id].tsx
> +    await apiPost("/etablissements/:id/premium/refuse", {
JAmais haha je le supprime le api.js

2023-10-05 12:25 UTC, antoinebigard commented on ui/pages/espace-pro/form/premium/[id].tsx
> +      const etablissement = (await apiGet("/etablissements/:id", {
JAmais haha je le supprime le api.js

2023-10-05 12:25 UTC, antoinebigard commented on ui/pages/espace-pro/form/premium/affelnet/[id].tsx
> +    await apiPost("/etablissements/:id/premium/affelnet/accept", {
JAmais haha je le supprime le api.js

2023-10-05 12:25 UTC, antoinebigard commented on ui/pages/espace-pro/form/premium/affelnet/[id].tsx
> +    await apiPost("/etablissements/:id/premium/affelnet/refuse", {
JAmais haha je le supprime le api.js

2023-10-05 12:26 UTC, antoinebigard commented on ui/pages/espace-pro/form/premium/affelnet/[id].tsx
> +      const etablissement = (await apiGet("/etablissements/:id", {
JAmais haha je le supprime le api.js

2023-10-05 12:32 UTC, antoinebigard commented on server/src/config.ts
> +        secure: env.get("LBA_AUTH_SESSION_COOKIE_SECURE").default("true").asBool(),
je vais plutot les enlever des var 👍

2023-10-05 15:20 UTC, antoinebigard commented on server/src/common/model/schema/session/session.schema.ts
> +    },
Parce que mongoose 💩

2023-10-05 15:21 UTC, antoinebigard commented on server/src/services/sessions.service.ts
> +  return Session.findOne(filter, options)
No need l'obj n'est pas utilisé

2023-10-05 15:22 UTC, antoinebigard commented on server/src/services/sessions.service.ts
> +  return Session.updateOne({ _id }, { $set: { ...data, updated_at: new Date() } })
No need l'obj n'est pas utilisé

2023-10-05 15:27 UTC, antoinebigard commented on shared/models/usersRecruteur.model.ts
> +    status_current: getUserStatus(user.status),
Pas la même route

2023-10-09 14:48 UTC, moroine requested changes
Partial review

2023-10-09 14:48 UTC, moroine commented on server/package.json
> +    "@types/netmask": "^2.0.3",
Pourquoi pas garder en `devDependencies`?

2023-10-09 14:48 UTC, moroine commented on server/src/common/model/schema/session/session.schema.ts
> +    },
Doit-on mettre un champs `expiresAt` avec un TTL index ?

2023-10-09 14:48 UTC, moroine commented on server/src/common/model/schema/session/session.schema.ts
> +sessionSchema.index({ token: 1 }, { name: "token" })
Pas besoin du name sur l'index. C'est mieux de laisser le name automatique pour éviter les conflits MongoDB.

2023-10-09 14:48 UTC, moroine commented on server/src/common/model/schema/session/session.types.ts
> +export type { ISession }
Le fichier peut etre removed, beaucoup plus simple d'import depuis `shared` directement

2023-10-09 14:48 UTC, moroine commented on server/src/config.ts
> +          .default(30 * 24 * 3600000)
Pas de defaut, mettre en `.required` il faut qu'on force les `.env` de définir les envs

2023-10-09 14:48 UTC, moroine commented on server/src/http/middlewares/authMiddleware.ts
> +  : AuthScheme extends "jwt-bearer" | "jwt-token" | "cookie-session"
Pourquoi pas juste `session` ? Par definition une session n'est pas toujours via cookie?

2023-10-09 14:48 UTC, moroine commented on server/src/http/middlewares/authMiddleware.ts
> +    return user
Il faut absoluement ajouter le TTL dans la collection. Car là on fait confiance à l'expiration du cookie, qui en soit peut etre recupérer et perpetuelement renouvelé par un hacker

2023-10-09 14:48 UTC, moroine commented on server/src/http/middlewares/authMiddleware.ts
> +const authorizationnAdmin = async (req: FastifyRequest) => {
Typo

2023-10-09 14:48 UTC, moroine commented on server/src/http/middlewares/authMiddleware.ts
> +}
```suggestion
  // @ts-expect-error: TODO
  if (req.user?.type !== "ADMIN") {
    throw Boom.unauthorized()
  }
}
```

2023-10-09 14:48 UTC, moroine commented on server/src/http/routes/admin/appointment.controller.ts
Remove directement alors non?

2023-10-09 14:48 UTC, moroine commented on server/src/http/routes/admin/appointment.controller.ts
> +      preHandler: [server.auth(zRoutes.get["/admin/appointments/details"].securityScheme)],
On voudrait pas plutot dans le `onRequest` ?

2023-10-09 14:48 UTC, moroine commented on server/src/http/routes/admin/appointment.controller.ts
> +        // }
Pourquoi? En soit ça ne doit jamais arriver je penses.

2023-10-09 14:48 UTC, moroine commented on server/src/http/routes/admin/etablissement.controller.ts
> +  //   }
Remove alors

2023-10-09 14:48 UTC, moroine commented on server/src/http/routes/admin/etablissement.controller.ts
> +  // )
Remove

2023-10-09 14:48 UTC, moroine commented on server/src/http/middlewares/authMiddleware.ts
> +    const session = await getSession({ token })
Le token de session est un token JWT, on peut le valider pour éviter une requete BDD et utiliser la requete BDD pour valider que le token n'a pas été supprimé.

On a en soit pas besoin de faire un `getSession` on veut juste un `Session.findOne({ token }, { projection: { _id: 0, token: 1 })` pour ne pas lire le disque mais juste tester l'existence.

2023-10-09 14:48 UTC, moroine commented on server/src/http/routes/auth/login.controller.ts
> +      preHandler: [server.auth(zRoutes.get["/auth/session"].securityScheme)],
`onRequest` hook

2023-10-09 14:48 UTC, moroine commented on server/src/http/routes/auth/login.controller.ts
> +      }
On peut move ça dans le `getUserFromRequest` non?

2023-10-09 14:48 UTC, moroine commented on server/src/http/routes/auth/login.controller.ts
> +      preHandler: [server.auth(zRoutes.get["/auth/logout"].securityScheme)],
`onRequest` hook

2023-10-09 14:48 UTC, moroine commented on server/src/http/routes/auth/login.controller.ts
> +      preHandler: [server.auth(zRoutes.get["/auth/logout"].securityScheme)],
Est-ce qu'on veut authentifier ? Si t'es pas connecté tu peut logout et ça plante pas IMO

2023-10-09 14:48 UTC, moroine commented on server/src/http/routes/etablissementRecruteur.controller.ts
> +      preHandler: [server.auth(zRoutes.post["/etablissement/validation"].securityScheme)],
`onRequest` hook

2023-10-09 14:48 UTC, moroine commented on server/src/http/routes/etablissementRecruteur.controller.ts
> +      await createSession({ token })
On peut avoir un seule fonction pour `createUserToken` + `createSession`

2023-10-09 14:48 UTC, moroine commented on server/src/http/routes/formulaire.controller.ts
> +      preHandler: [server.auth(zRoutes.put["/formulaire/:establishment_id"].securityScheme)],
`onRequest` hook

2023-10-09 14:48 UTC, moroine commented on server/src/http/routes/formulaire.controller.ts
> +      // preHandler: [server.auth(zRoutes.post["/formulaire/:establishment_id/offre"].securityScheme)],
Pourquoi?

2023-10-09 14:48 UTC, moroine commented on server/src/http/routes/user.controller.ts
> +      return res.status(200).send({})
On remove ou on fixe?

2023-10-09 14:48 UTC, moroine commented on server/src/http/routes/user.controller.ts
> +      return res.status(200).send({})
On remove ou on fixe?

2023-10-09 14:48 UTC, moroine commented on server/src/http/routes/user.controller.ts
> +      preHandler: [server.auth(zRoutes.get["/user/:userId"].securityScheme)],
`onRequest` hook

2023-10-09 14:48 UTC, moroine commented on server/src/http/routes/user.controller.ts
> +      if (!user) return res.status(400).send({})
Throw Boom ?

2023-10-09 14:48 UTC, moroine commented on server/src/http/routes/user.controller.ts
> +      schema: zRoutes.get["/user/status/:userId"],
Missing auth?

2023-10-09 14:48 UTC, moroine commented on server/src/http/routes/user.controller.ts
> +      preHandler: [server.auth(zRoutes.put["/user/:userId"].securityScheme)],
`onRequest` hook

2023-10-09 14:48 UTC, moroine commented on server/src/services/etablissement.service.ts
> +const getValidationUrl = (_id: IRecruiter["_id"], email): string => {
```suggestion
/**
 * Get the establishment validation url for a given SIRET
 */
const getValidationUrl = (_id: IRecruiter["_id"], email: string): string => {
```

2023-10-09 14:48 UTC, moroine commented on server/src/services/sessions.service.ts
> +  return session
```suggestion
  const now = new Date()

  const session = new Session({
    ...data,
    updated_at: now,
    created_at: now,
  })
  await session.save()

  return session
```

2023-10-09 14:48 UTC, moroine commented on server/src/services/sessions.service.ts
> +  await Session.deleteMany({ token })
`Many` ? Est-ce qu'on mettrait pas un `unique` index sur `token` ?

2023-10-09 14:48 UTC, moroine commented on server/src/services/sessions.service.ts
> +  return Session.updateOne({ _id }, { $set: { ...data, updated_at: new Date() } })
Dans quel contexte t'as besoin de update?

2023-10-09 14:48 UTC, moroine commented on shared/models/session.model.ts
> +    created_at: z.date().optional().describe("Date d'ajout en base de données"),
Pas `optional`

2023-10-09 14:48 UTC, moroine commented on shared/models/usersRecruteur.model.ts
> +  status_current: z.enum([etatUtilisateurValues[0], ...etatUtilisateurValues.slice(1)]).nullable(),
Je comprends pas le `slice` ect...

2023-10-09 14:48 UTC, moroine commented on shared/models/usersRecruteur.model.ts
> +  return lastValidationEvent.status
osef, mais en soit pas besoin de sort `O(n*ln(n))` vs `O(n)`

2023-10-09 14:48 UTC, moroine commented on shared/routes/appointments.routes.ts
> +    // },
Remove

2023-10-09 14:48 UTC, moroine commented on shared/routes/etablissement.routes.ts
> +    // TODO NOT USED TO DELETE
Remove

2023-10-09 14:48 UTC, moroine commented on shared/routes/etablissement.routes.ts
> +    // TODO NOT USED TO DELETE
Remove

2023-10-09 14:48 UTC, moroine commented on shared/routes/formulaire.route.ts
> +        auth: "none", // "cookie-session",
Soit tu remove le `TODO_SECURITY_FIX` ou tu actives le `cookie-session`

2023-10-09 14:48 UTC, moroine commented on shared/routes/login.routes.ts
> +        "2xx": z.any(),
Pourquoi `any` tu connais précisement non?

2023-10-10 09:44 UTC, moroine requested changes

2023-10-10 09:44 UTC, moroine commented on shared/routes/login.routes.ts
> +        // TODO ANY TO BE FIXED
Pourquoi `any` tu connais précisement non?

2023-10-10 09:44 UTC, moroine commented on shared/routes/login.routes.ts
> +        // TODO ANY TO BE FIXED
Pourquoi `any` tu connais précisement non?

2023-10-10 09:44 UTC, moroine commented on shared/routes/recruiters.routes.ts
> +        auth: "jwt-token",
Check

2023-10-10 09:44 UTC, moroine commented on server/src/http/routes/formulaire.controller.ts
> +      // TODO no security ?
@kevbarns  ?

2023-10-10 09:44 UTC, moroine commented on shared/routes/recruiters.routes.ts
> +        "2xx": z.any(),
Pourquoi `any` tu connais précisement non?

2023-10-10 09:44 UTC, moroine commented on shared/routes/user.routes.ts
> +      },
Pourquoi `any` tu connais précisement non?

2023-10-10 09:44 UTC, moroine commented on shared/routes/user.routes.ts
> +      // TODO ANY TO BE FIXED
Pourquoi `any` tu connais précisement non?

2023-10-10 09:44 UTC, moroine commented on shared/routes/user.routes.ts
> +      body: z.any(),
Pourquoi `any` tu connais précisement non?

2023-10-10 09:44 UTC, moroine commented on ui/common/SSR/getAuthServerSideProps.ts
> +    })
Si pas de `cookie` header ne pas tenter l'auth

2023-10-10 09:44 UTC, moroine commented on ui/components/espace_pro/Admin/utilisateurs/UserForm.tsx
> +      // await apiPut("/admin/users/:userId", { params: { userId: user._id }, body })
Pourquoi comment?

2023-10-10 09:44 UTC, moroine commented on ui/components/espace_pro/Admin/utilisateurs/UserForm.tsx
> +      // await _post(`/api/v1/admin/users/${user._id}/resend-confirmation-email`)
Pourquoi comment?

2023-10-10 11:49 UTC, antoinebigard commented on server/package.json
> +    "@types/netmask": "^2.0.3",
ça guelait sur le install

2023-10-10 11:56 UTC, antoinebigard commented on shared/routes/recruiters.routes.ts
> +        auth: "jwt-token",
✅

2023-10-10 11:56 UTC, antoinebigard commented on server/src/config.ts
> +        secure: env.get("LBA_AUTH_SESSION_COOKIE_SECURE").default("true").asBool(),
✅

2023-10-10 11:56 UTC, antoinebigard commented on server/src/common/model/schema/session/session.schema.ts
> +sessionSchema.index({ token: 1 }, { name: "token" })
✅

2023-10-10 11:56 UTC, antoinebigard commented on server/src/common/model/schema/session/session.types.ts
> +export type { ISession }
✅

2023-10-10 11:56 UTC, antoinebigard commented on server/src/config.ts
> +          .default(30 * 24 * 3600000)
✅

2023-10-10 11:56 UTC, antoinebigard commented on shared/routes/appointments.routes.ts
> +    // },
✅

2023-10-10 11:56 UTC, antoinebigard commented on shared/routes/etablissement.routes.ts
> +    // TODO NOT USED TO DELETE
✅

2023-10-10 11:56 UTC, antoinebigard commented on shared/routes/etablissement.routes.ts
> +    // TODO NOT USED TO DELETE
✅

2023-10-10 11:56 UTC, antoinebigard commented on shared/routes/formulaire.route.ts
> +        auth: "none", // "cookie-session",
✅

2023-10-10 12:03 UTC, antoinebigard commented on ui/common/SSR/getAuthServerSideProps.ts
> +    })
✅

2023-10-10 12:03 UTC, antoinebigard commented on ui/components/espace_pro/Admin/utilisateurs/UserForm.tsx
> +      // await apiPut("/admin/users/:userId", { params: { userId: user._id }, body })
partie pas terminée

2023-10-10 12:03 UTC, antoinebigard commented on ui/components/espace_pro/Admin/utilisateurs/UserForm.tsx
> +      // await _post(`/api/v1/admin/users/${user._id}/resend-confirmation-email`)
partie pas terminée

2023-10-10 12:20 UTC, antoinebigard commented on server/src/common/model/schema/session/session.schema.ts
> +    },
@moroine peux tu check rapido le last commit stp

2023-10-10 12:21 UTC, antoinebigard commented on shared/routes/login.routes.ts
> +        // TODO ANY TO BE FIXED
❌

2023-10-10 12:21 UTC, antoinebigard commented on shared/routes/login.routes.ts
> +        // TODO ANY TO BE FIXED
❌

2023-10-10 12:21 UTC, antoinebigard commented on shared/routes/recruiters.routes.ts
> +        "2xx": z.any(),
❌

2023-10-10 12:21 UTC, antoinebigard commented on shared/routes/user.routes.ts
> +      // TODO ANY TO BE FIXED
❌

2023-10-10 12:21 UTC, antoinebigard commented on shared/routes/user.routes.ts
> +      body: z.any(),
❌

2023-10-10 12:28 UTC, moroine commented on server/src/common/model/schema/session/session.schema.ts
> +sessionSchema.index({ expires_at: 1 }, { expireAfterSeconds: config.auth.session.cookie.maxAge / 100 })
Non ici, soit tu fais `expireAfterSeconds: 0` et tu set le `expires_at` en fonction (donc pas `Date.now`) soit tu fais 
```suggestion
sessionSchema.index({ updated_at: 1 }, { expireAfterSeconds: config.auth.session.cookie.maxAge / 100 })
```

--> Et tu remove le champs

2023-10-10 12:28 UTC, moroine commented on ui/common/SSR/getAuthServerSideProps.ts
> +  console.log(context.req.headers)
console.log

2023-10-10 12:28 UTC, moroine commented on ui/common/utils/emitter.ts
> +const subscribeToHttpEvent = (eventName, callback) => emitter.on(eventName, callback)
C'est utilisé où ? Attention ici c'est une memory leak tu unsuscribe jamais?

2023-10-10 12:29 UTC, antoinebigard commented on server/src/common/model/schema/session/session.schema.ts
> +sessionSchema.index({ expires_at: 1 }, { expireAfterSeconds: config.auth.session.cookie.maxAge / 100 })
c'est set mais justement cest le default pour etre certains

2023-10-10 12:29 UTC, antoinebigard commented on ui/common/SSR/getAuthServerSideProps.ts
> +  console.log(context.req.headers)
yes yes vu juste apres

2023-10-10 12:32 UTC, antoinebigard commented on ui/common/utils/emitter.ts
> +const subscribeToHttpEvent = (eventName, callback) => emitter.on(eventName, callback)
UserContext => wrap l'ensemble => unmount == emitter.off

2023-10-10 12:32 UTC, antoinebigard commented on ui/common/utils/emitter.ts
> +const subscribeToHttpEvent = (eventName, callback) => emitter.on(eventName, callback)
UserContext => wrap l'ensemble => unmount == emitter.off

2023-10-10 13:04 UTC, merged