fix: add cron jobs
mission-apprentissage/labonnealternance pull request #640
Opened 2023-10-06 09:01 UTC by moroine

https://github.com/mission-apprentissage/labonnealternance-infra/blob/main/ansible/roles/setup/tasks/create-cron.yml

2023-10-06 11:01 UTC, alanlr requested changes

2023-10-06 11:01 UTC, alanlr commented on server/src/jobs/jobs.ts
> +  "Reindex formulaire collection": {
ok pour celles là mais il en manque pas mal

2023-10-06 11:01 UTC, alanlr commented on server/src/jobs/jobs.ts
> +  "Reindex formulaire collection": {
je pense qu'il faut les pêcher directement dans les confs exclusives de la prod.

2023-10-06 13:55 UTC, remy-auricoste commented on server/src/jobs/crons_actions.ts
> +  )) as IInternalJobsCron[]
je pense qu'il vaut mieux typer correctement la fonction `findJobs`

2023-10-06 13:55 UTC, remy-auricoste commented on server/src/jobs/job.actions.ts
> +  return { ...job, _id } as IInternalJobsSimple
```suggestion
  return { ...job, _id }
```

2023-10-06 14:52 UTC, alanlr requested changes

2023-10-06 14:52 UTC, alanlr commented on server/src/jobs/jobs.ts
> +    cron_string: "30 0 * * * 1,3,5",
une * de trop cf. https://crontab.guru/#30_0_*_*_1,3,5

2023-10-06 14:52 UTC, alanlr commented on server/src/jobs/jobs.ts
> +    cron_string: "45 23 * * * 2",
une * de trop

2023-10-06 14:52 UTC, alanlr commented on server/src/jobs/jobs.ts
> +    cron_string: "0 5 * * * 6",
une * de trop

2023-10-06 14:52 UTC, alanlr commented on server/src/jobs/jobs.ts
> +    cron_string: "30 6 * * * 6",
une * de trop

2023-10-06 15:44 UTC, remy-auricoste commented on server/src/jobs/jobs.ts
> +  "Send CSV offers to Pôle emploi": {
je vois que certains cron n'étaient activés que sur la prod. Est ce que le fait de les activer sur tous les envs ne peut pas poser problème (appel d'api...) ?

2023-10-06 15:44 UTC, remy-auricoste commented on server/src/jobs/jobs.ts
> +    handler: () => addJob({ name: "siret:inError:update", payload: { threshold: "1" } }),
```suggestion
    handler: () => addJob({ name: "siret:inError:update", payload: {  } }),
``` ?

2023-10-06 21:01 UTC, moroine commented on server/src/jobs/crons_actions.ts
> +  )) as IInternalJobsCron[]
TypeScript n'est pas assez intelligent... Il décorèle `payload` de `name` du coup il me dit que ça marche pas

2023-10-06 21:02 UTC, moroine commented on server/src/jobs/job.actions.ts
> +  return { ...job, _id } as IInternalJobsSimple
TypeScript n'est pas assez intelligent... Il décorèle `payload` de `name` du coup il me dit que ça marche pas

2023-10-06 21:10 UTC, moroine commented on server/src/jobs/jobs.ts
> +    handler: () => addJob({ name: "siret:inError:update", payload: { threshold: "1" } }),
Hum, `Pick` ne fonctionne pas comme attendu... Ici, il veut une payload n'importe laquelle et il valide pas avec le name...

2023-10-06 21:10 UTC, moroine commented on server/src/jobs/jobs.ts
> +  "Send CSV offers to Pôle emploi": {
J'en sais rien

2023-10-09 05:05 UTC, antoinebigard commented
L'enfer cette PR ! 
Je comprends l'envie de tout typer mais franchement celle la est TOO much  
Des any pour des payload de commandes ça fait largement le taff + avoir une collection "uncontrolled" de job interne sur les payload etc.. c'est tout à fait acceptable. 

Cette PR est un over kill et ça complexifie bcp. 
C'est la pr qui montre la limite du typing => la c'est beaucoup trop !
 
Il faut simplifier.  genre InternalJobSimple<BLABLA le nom du job etc..> re-re-re-re definition

2023-10-09 05:06 UTC, antoinebigard requested changes
Voir ci-dessus

2023-10-09 08:06 UTC, alanlr commented on server/src/jobs/jobs.ts
> +  "Send CSV offers to Pôle emploi": {
vu irl à l'isntant

2023-10-09 13:54 UTC, kevbarns approved these changes

2023-10-09 18:57 UTC, merged