feat: ajout de fallback pour l'api geo coord
mission-apprentissage/labonnealternance pull request #641
Opened 2023-10-06 09:02 UTC by remy-auricoste

2023-10-06 10:53 UTC, alanlr requested changes

2023-10-06 10:53 UTC, alanlr commented on server/src/services/etablissement.service.ts
> +      throw new Error("pas trouvé")
Je rajouterai une étape avec une recherche sur le couple `${ville} ${cp}`  en prenant la first feature et là à défaut --> boom

2023-10-06 15:36 UTC, remy-auricoste commented on server/src/services/etablissement.service.ts
> +      throw new Error("pas trouvé")
j'ai ajouté le fallback

2023-10-06 15:36 UTC, remy-auricoste commented on server/src/services/etablissement.service.ts
> +  const geo_coordinates = await getGeoCoordinates(`${numeroEtRue}, ${codePostalEtVille}`).catch(() => getGeoCoordinates(codePostalEtVille))
le fallback est ici

2023-10-13 07:03 UTC, alanlr commented on server/src/services/etablissement.service.ts
> +  return { ...entrepriseData, geo_coordinates: geo_coordinates.join(",") }
je te ping à propos du first + second et du join sur cette ligne car j'ai un doute sur un truc

2023-10-13 09:26 UTC, alanlr approved these changes

2023-10-16 07:17 UTC, merged