fix: LBAC-1694 améliorations html diverses
mission-apprentissage/labonnealternance pull request #812
Opened 2023-11-13 23:08 UTC by alanlr

2023-11-13 23:10 UTC, alanlr commented
🚀

2023-11-14 09:11 UTC, remy-auricoste approved these changes

2023-11-15 08:01 UTC, remy-auricoste requested changes

2023-11-15 08:01 UTC, remy-auricoste commented on ui/components/espace_pro/Proposition/Offre/PropositionOffreId.tsx
> +      const { data }: any = await getFormulaire(idFormulaire)
Je pense qu'il faut revert ce changement

2023-11-15 08:20 UTC, alanlr commented
🚀

2023-11-15 09:26 UTC, alanlr commented
🚀

2023-11-15 13:57 UTC, closed without merging

2023-11-15 13:58 UTC, alanlr commented
fichiers parasites suite à un merge