feat: LBAC-1704 tests end to end sur la recette
mission-apprentissage/labonnealternance pull request #825
Opened 2023-11-17 16:44 UTC by alanlr

2023-11-20 14:49 UTC, alanlr commented
🚀

2023-11-20 15:11 UTC, alanlr commented
🚀

2023-11-21 08:48 UTC, moroine requested changes

2023-11-21 08:48 UTC, moroine commented on .github/workflows/cypress.yml
> +        description: Wehook slack
```suggestion
        description: Webhook slack
```

2023-11-21 08:48 UTC, moroine commented on .github/workflows/cypress.yml
> +on:
Si tu veux tester tu peux essayer:
```suggestion
on:
  workflow_dispatch:
    inputs:
      cypress_host:
        description: host name
        type: string
        required: true
    secrets:
      CODECOV_TOKEN:
        description: Code coverrage token
        required: true
      SLACK_WEBHOOK:
        description: Webhook slack
        required: true
```

2023-11-21 08:48 UTC, moroine commented on .github/workflows/cypress.yml
> +      if: ${{ inputs.environment }} == 'recette'
Je penses qu'il te faut `failure` car par default en failure ça skip les steps suivants
```suggestion
      if: ${{ failure() }} && ${{ inputs.environment }} == 'recette'
```

2023-11-21 08:48 UTC, moroine commented on .github/workflows/deploy_preview.yml
> +    if: (startsWith(github.event.comment.body, '🚀') || startsWith(github.event.comment.body, ':rocket:')) && github.event.issue.pull_request
Je penses pas que la condition soit nécessaire. Vu le step `deploy_preview` est skip, la dépendance fera que ce step sera skip

2023-11-21 08:48 UTC, moroine commented on .github/workflows/release.yml
> +    inputs:
Il manque le `needs` pour tester apres deploiement

2023-11-21 08:48 UTC, moroine commented on cypress.config.ts
> +  // },
Pourquoi pas supprimer carrément?

2023-11-21 10:25 UTC, alanlr commented on .github/workflows/deploy_preview.yml
> +    if: (startsWith(github.event.comment.body, '🚀') || startsWith(github.event.comment.body, ':rocket:')) && github.event.issue.pull_request
ok vu

2023-11-21 10:26 UTC, alanlr commented on .github/workflows/release.yml
> +    inputs:
Oui j'avais vu qu'il manquait ça car les tests étaient ok mais semblaient juste dire ok à "rien" ;-)

2023-11-21 10:28 UTC, alanlr commented on .github/workflows/cypress.yml
> +      if: ${{ inputs.environment }} == 'recette'
Du coup failure() va rattraper ce qui aurait dû être skippé ?

2023-11-21 10:53 UTC, alanlr commented
🚀

2023-11-21 11:15 UTC, moroine approved these changes

2023-11-21 11:20 UTC, merged