feat: Pseudonymisation collections
mission-apprentissage/labonnealternance pull request #859
Opened 2023-11-27 09:26 UTC by alanlr

2023-11-27 13:14 UTC, antoinebigard commented on server/src/jobs/database/obfuscateCollections.ts
> +      applicant_email: "faux_email@faux-domaine.fr",
Il faudrait garder l'unicité du coup F42A924ACE@D34FBC18.fr

2023-11-27 13:14 UTC, antoinebigard commented on server/src/jobs/database/obfuscateCollections.ts
> +      company_email: "faux_email@faux-domaine-compagnie.com",
F42A924ACE@D34FBC18-company.fr

2023-11-27 13:31 UTC, moroine commented on server/src/common/model/schema/application/anonymizedApplications.schema.ts
> -export default model<IAnonymizedApplication, Pagination<IAnonymizedApplication>>("applications", anonymizedApplicationSchema)
Y'a un impact en prod?

2023-11-27 13:31 UTC, moroine commented on server/src/jobs/database/obfuscateCollections.ts
> +      { $project: { _id: 0, minDate: 1 } },
```suggestion
      { $match: {} },
      { $sort: { created_at: -1 } },
      { $skip: limit },
      { $limit: 1 },
      { $project: { _id: 0, minDate: '$created_at' } },
```

2023-11-27 13:31 UTC, moroine commented on server/src/jobs/database/obfuscateCollections.ts
> +    }
Aucune autre collection ne reference les applications ?

2023-11-27 13:31 UTC, moroine commented on server/src/jobs/database/obfuscateCollections.ts
> +    }
Est-ce que plutot on pourrait pas utiliser le script `anonymise` qui sera lui beaucoup plus maintenu? En soit, on anonymise les applications et ça devrait etre le expected (puis on clear la collection d'historique).

2023-11-27 13:31 UTC, moroine commented on server/src/jobs/database/obfuscateCollections.ts
> +  )
```suggestion
  const applicationEmails = Application.aggregate([
     { $group: {._id: '$applicant_email' } },
  ]).toArray();  
  const userEmails = await User.aggregate([
     { $group: {._id: '$email' } },
  ]).toArray();
  
  const uniqueEmailCandidat = new Set([...applicationEmails, ...userEmails]);
  
  const generateCandidat = () => {
    return {
       email: faker.email(),
       phone: faker.phone(),
       firstName: faker.firstName(),
       lastName: faker.lastName(),
    }
  }
  
  for await (const originalEmail of uniqueEmailCandidat) {
     const candidat = generateCandidat();
     await Application.updateMany({
         applicant_email: originalEmail,
     }, { $set: candidat }):
     await User.updateMany({
         applicant_email: originalEmail,
     }, { $set: candidat }):
  }
```

2023-11-27 13:32 UTC, alanlr commented on server/src/common/model/schema/application/anonymizedApplications.schema.ts
> -export default model<IAnonymizedApplication, Pagination<IAnonymizedApplication>>("applications", anonymizedApplicationSchema)
non

2023-11-27 14:37 UTC, alanlr commented on server/src/jobs/database/obfuscateCollections.ts
> +      { $project: { _id: 0, minDate: 1 } },
Done

2023-11-27 14:38 UTC, alanlr commented on server/src/jobs/database/obfuscateCollections.ts
> +    }
Non pas de référence directe par les données anonymisées des candidatures.
Cf. discussion slack pour le deuxième sujet.

2023-11-28 08:46 UTC, moroine commented on server/src/jobs/database/obfuscateCollections.ts
> +}
```suggestion
const getFakeEmail = async (collection: string, provider?: string) => {
  let email = `faker-${provider ? faker.internet.email({ provider }) : faker.internet.email()}`
  const exists = await db.collection(collection).countDocuments({ email })
  if (!exists) {
    return email;
  }
 
 return getFakeEmail(collection, provider);
}
```

2023-11-28 08:46 UTC, moroine commented on server/src/jobs/database/obfuscateCollections.ts
> +  })
On peut éviter de tout charger en RAM, et commencer avant d'avoir l'ensemble des résultats:

```suggestion
  const users: AsyncIterable<IUserRecruteur> = db.collection("userrecruteurs").find({})
  
  for await (const user of users) {
    let fakeEmail = ""
    switch (user.type) {
      case OPCO: {
        fakeEmail = await getFakeEmail("userrecruteurs", "opco.fr")
        break
      }
      case ADMIN: {
        fakeEmail = await getFakeEmail("userrecruteurs", "admin.fr")
        break
      }
      default: {
        // CFA ou ENTREPRISE
        fakeEmail = await getFakeEmail("userrecruteurs")
        break
      }
    }
    
    const replacement = { $set: { email: fakeEmail, phone: "0601010106", last_name: "nom_famille", first_name: "prenom" } }

    switch (user.type) {
      case ENTREPRISE: {
        await Promise.all([
          db.collection("userrecruteurs").findOneAndUpdate({ _id: user._id }, replacement),
          db.collection("recruiters").findOneAndUpdate({ establishment_id: user.establishment_id }, replacement),
        ])
        break
      }
      case CFA: {
        await Promise.all([
          db.collection("userrecruteurs").findOneAndUpdate({ _id: user._id }, replacement),
          db.collection("recruiters").updateMany({ cfa_delegated_siret: user.establishment_siret }, replacement),
        ])
        break
      }

      default: {
        await db.collection("userrecruteurs").findOneAndUpdate({ _id: user._id }, replacement)
        break
      }
    }
  }
```

2023-11-28 08:46 UTC, moroine commented on server/src/jobs/database/obfuscateCollections.ts
> +  await asyncForEach(users, async (user) => {
```suggestion
  const users: AsyncIterable<IUser> = await db.collection("users").find({})

  for await (const user of users) {
```

2023-11-28 08:46 UTC, moroine commented on server/src/jobs/database/obfuscateCollections.ts
> +  await reduceModel(ApiCalls)
Pourquoi pas de second param? Je penses qu'il y a un default param mais c'est mieux je penses si c'est explicite ici

2023-11-28 09:08 UTC, alanlr commented on server/src/jobs/database/obfuscateCollections.ts
> +  await reduceModel(ApiCalls)
ok, en effet c'était une valeur par défaut.

2023-11-28 09:08 UTC, alanlr commented on server/src/jobs/database/obfuscateCollections.ts
> +  await asyncForEach(users, async (user) => {
j'applique les deux dernières suggestions.

2023-11-28 09:25 UTC, moroine requested changes

2023-11-28 09:25 UTC, moroine commented on server/src/jobs/database/obfuscateCollections.ts
> +const getFakeEmail = async () => `${randomUUID()}@${faker.internet.domainName()}`
Mais pourquoi pas simplement utiliser `faker.internet.email()`?

2023-11-28 09:25 UTC, moroine commented on server/src/jobs/database/obfuscateCollections.ts
> +  const users: IUserRecruteur[] = await db.collection("userrecruteurs").find({}).toArray()
@kevbarns ne pas utiliser `toArray` ça ralenti et charge tout en RAM

2023-11-28 09:25 UTC, moroine commented on server/src/jobs/database/obfuscateCollections.ts
> +  const users: IUser[] = await db.collection("users").find({}).toArray()
@kevbarns ne pas utiliser `toArray` ça ralenti et charge tout en RAM

2023-11-28 09:25 UTC, remy-auricoste commented on server/src/jobs/database/obfuscateCollections.ts
> +      }
```suggestion
      case CFA:
      case ENTREPRISE: {
        await Promise.all([
          db.collection("userrecruteurs").findOneAndUpdate({ _id: user._id }, replacement),
          db.collection("recruiters").findOneAndUpdate({ establishment_id: user.establishment_id }, replacement),
        ])
        break
      }
```

2023-11-28 09:26 UTC, remy-auricoste approved these changes

2023-11-28 15:25 UTC, alanlr commented on server/src/jobs/database/obfuscateCollections.ts
> +      }
C'est pas les mêmes traitements pour CFA et ENTREPRISE

2023-11-28 17:45 UTC, remy-auricoste commented on server/src/jobs/database/obfuscateCollections.ts
> +      }
effectivement, j'avais pas les yeux en face des trous ><

2023-11-29 10:35 UTC, merged