Refacto:  lba seed job
mission-apprentissage/labonnealternance pull request #87
Opened 2022-11-30 14:52 UTC by kevbarns

Cette PR a pour objectif de clarifier le code des jobs d'import nécéssaire au bon fonctionnement de la partie Candidat de LBA. 
- Prévoir l'intégration de la méthode _scroll d'ElasticSearch pour améliorer les performances sur les large set de données contenue dans l'ES.

2022-11-30 15:10 UTC, alanlr requested changes

2022-11-30 15:10 UTC, alanlr commented on server/src/jobs/importFormationsCatalogue/importFormationsCatalogue.js
> +    await client.indices.delete({ index })
il faut remettre un try catch. Sinon il me semble que l'erreur est bloquante alors qu'un index inexistant représente l'état vierge normal.

2022-11-30 15:10 UTC, alanlr commented on server/src/jobs/importFormationsCatalogue/importFormationsCatalogue.js
> -        if (stats.total % 1000 === 0) {
dommage de perdre cette forme de barre de progression pour un script si long.

2022-11-30 15:10 UTC, alanlr commented on server/src/jobs/importFormationsCatalogue/importFormationsCatalogue.js
> -      notifyToSlack(`Import formations catalogue terminé sur ${workIndex}. ${stats.created} OK. ${stats.failed} erreur(s)`)
A remettre.

2022-11-30 15:10 UTC, alanlr commented on server/src/jobs/importFormationsCatalogue/importFormationsCatalogue.js
> -      notifyToSlack(`ECHEC Import formations catalogue. ${error_msg}`)
Idem à remettre

2022-11-30 16:26 UTC, kevbarns commented on server/src/jobs/importFormationsCatalogue/importFormationsCatalogue.js
> -      notifyToSlack(`ECHEC Import formations catalogue. ${error_msg}`)
idem

2022-11-30 16:26 UTC, kevbarns commented on server/src/jobs/importFormationsCatalogue/importFormationsCatalogue.js
> -      notifyToSlack(`Import formations catalogue terminé sur ${workIndex}. ${stats.created} OK. ${stats.failed} erreur(s)`)
On envoie pas une alerte slack sur un job de seed.

2022-11-30 16:38 UTC, kevbarns commented on server/src/jobs/importFormationsCatalogue/importFormationsCatalogue.js
> +    await client.indices.delete({ index })
c'est déjà dans un try/catch

2022-11-30 16:41 UTC, kevbarns commented on server/src/jobs/importFormationsCatalogue/importFormationsCatalogue.js
> -        if (stats.total % 1000 === 0) {
la fonction console.log() est synchrone, donc elle bloque l'Event loop, ou du moins elle entre y systématiquement entre chaque appel et dans le cas présent, si la condition est vérifier, qui elle aussi est évalué systématiquement.

2022-12-01 13:15 UTC, alanlr approved these changes

2022-12-01 13:15 UTC, alanlr commented on server/src/jobs/lbb/updateOpcoCompanies.js
> +      await notifyToSlack({ subject: "", message: `Fin d'insertion des SIRENs akto (${i})` })
Subject à "" ?

2022-12-01 14:07 UTC, merged

2023-03-14 15:23 UTC, kevbarns commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.0.0)
- `v1.0.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: