feat: chakraisation des formulaires de recherche
mission-apprentissage/labonnealternance pull request #89
Opened 2022-12-01 09:44 UTC by alanlr

2022-12-01 13:49 UTC, kevbarns commented on ui/components/WidgetHeader/WidgetHeader.js
> +        {isHome ? "" : <LogoIdea />}
`{ishome && <LogoIdea />}`

2022-12-01 13:50 UTC, kevbarns commented on ui/components/WidgetHeader/WidgetHeader.js
> +          )}
idem que le commentaire précédent

2022-12-01 13:51 UTC, kevbarns commented on ui/components/HeaderForm/HeaderForm.js
> +                  )}
utiliser l'opérateur AND logique ( && ) si pas de condition false

2022-12-01 13:53 UTC, kevbarns commented on ui/components/ItemDetail/LbbCompany.js
>              {company.place.distance ? `${company.place.distance} km(s) du lieu de recherche` : ""}
L'opérateur AND logique ( && )

2022-12-01 13:53 UTC, kevbarns commented on ui/components/ItemDetail/LbbCompany.js
> +              </Text>
L'opérateur AND logique ( && )

2022-12-01 13:53 UTC, kevbarns commented on ui/components/ItemDetail/LbbCompany.js
>            {showTextOnly ? "" : <>{Math.round(company.place.distance) > currentSearchRadius ? getCenterSearchOnCompanyButton() : ""}</>}
L'opérateur AND logique ( && )

2022-12-01 13:54 UTC, kevbarns commented on ui/components/ItemDetail/Training.js
>              {training.place.distance !== null ? `${Math.round(training.place.distance)} km(s) du lieu de recherche` : ""}
L'opérateur AND logique ( && )

2022-12-01 13:54 UTC, kevbarns commented on ui/components/ItemDetail/Training.js
> +              </Text>
L'opérateur AND logique ( && )

2022-12-01 13:54 UTC, kevbarns commented on ui/components/ItemDetail/Training.js
>            )}
L'opérateur AND logique ( && )

2022-12-01 13:55 UTC, kevbarns commented on ui/components/SearchForTrainingsAndJobs/components/SearchForm.js
> +      )}
utiliser l'opérateur AND logique ( && )

2022-12-01 13:57 UTC, kevbarns requested changes
utiliser l'opérateur AND logique ( && ) sur les conditions n'ayant pas de condition `false`

2022-12-01 21:28 UTC, alanlr commented on ui/components/WidgetHeader/WidgetHeader.js
> +        {isHome ? "" : <LogoIdea />}
ok !isHome.

2022-12-02 08:19 UTC, kevbarns approved these changes

2022-12-02 08:53 UTC, merged

2023-03-14 15:23 UTC, kevbarns commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.0.0)
- `v1.0.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: