feat: cli et cron jobs lbac
mission-apprentissage/labonnealternance pull request #91
Opened 2022-12-01 19:00 UTC by alanlr

2022-12-02 08:22 UTC, kevbarns commented on server/src/cli.js
> +  .command("anonymize-1-year-old-applications")
`anonymize-applications` pour la commande, la description est la pour fournir d'avantage d'informations

2022-12-02 08:23 UTC, kevbarns commented on server/src/cli.js
> +  .command("update-sendinblue-blocked-email-addresses")
`sync-sib-hardbounce`

2022-12-02 08:30 UTC, kevbarns commented on server/src/jobs/anonymizeOldApplications/anonymizeOldApplications.js
> +    logger.error(err)
Catcher l'erreur sur Sentry en premier

2022-12-02 08:30 UTC, kevbarns commented on server/src/jobs/anonymizeOldApplications/index.js
> +  await anonymizeOldApplications({ query: {} })
le paramètre est inutile car jamais lu

2022-12-02 08:31 UTC, kevbarns requested changes
👍

2022-12-02 08:32 UTC, kevbarns commented on server/src/cli.js
> +  .command("import-trainings-from-catalogue")
syc-catalogue-trainings

2022-12-02 08:41 UTC, alanlr commented on server/src/cli.js
> +  .command("update-sendinblue-blocked-email-addresses")
ok plutôt sync-sib-blocked alors car techniquement ce ne sont pas les hardbounces mais bien les adresses bloquées. Les hardbounces sont gérés par ailleurs au fil de l'eau.

2022-12-02 09:06 UTC, kevbarns approved these changes

2022-12-02 09:37 UTC, merged

2023-03-14 15:22 UTC, kevbarns commented
:tada: This PR is included in version 1.0.0 :tada:

The release is available on:
- [GitHub release](https://github.com/mission-apprentissage/labonnealternance/releases/tag/v1.0.0)
- `v1.0.0`

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: