feat: LBAC-1855 optimisation enregistrement stats visu des offres
mission-apprentissage/labonnealternance pull request #921
Opened 2023-12-13 21:28 UTC by alanlr

2023-12-14 07:10 UTC, kevbarns approved these changes

2023-12-14 08:45 UTC, alanlr commented
🚀

2023-12-14 17:51 UTC, alanlr commented
🚀

2023-12-18 10:18 UTC, alanlr commented
🚀

2023-12-18 12:51 UTC, kevbarns requested changes

2023-12-18 12:51 UTC, kevbarns commented on server/src/services/formulaire.service.ts
> +import { mongooseInstance } from "@/common/mongodb"
```suggestion
import { db } from "@/common/mongodb"
```

2023-12-18 12:51 UTC, kevbarns commented on server/src/services/formulaire.service.ts
> +  await mongooseInstance.connection.collection("recruiters").findOneAndUpdate(
```suggestion
  await db.collection("recruiters").findOneAndUpdate(
```

2023-12-18 13:21 UTC, kevbarns approved these changes

2023-12-19 08:18 UTC, alanlr commented
🚀

2023-12-19 09:20 UTC, alanlr commented
🚀

2023-12-19 09:41 UTC, alanlr commented
🚀

2023-12-19 10:01 UTC, merged