feat: control user state at each request
mission-apprentissage/labonnealternance pull request #930
Opened 2023-12-15 10:28 UTC by kevbarns

[YesWeHack-4] Un compte admin désactivé peut toujours accéder à la plateforme
- https://mna-matcha.atlassian.net/browse/LBAC-1859

2023-12-15 10:53 UTC, moroine reviewed
T'as testé le depot d'offre d'un recruteur non validé ?

2023-12-15 15:17 UTC, moroine requested changes

2023-12-15 15:17 UTC, moroine commented on server/src/http/middlewares/errorMiddleware.ts
> +      stopSession(_request, reply)
Il manque pas un await ici ? Est-ce que le erroHandler peut etre async ? Sinn il faut un `.catch` IMO et changer le stopSession pour que l'update du cookie soit fait de facon synchone (avant le await).

2023-12-15 15:17 UTC, moroine commented on server/src/http/routes/auth/login.controller.ts
> +        throw Boom.notFound()
`Boom.unauthorised()` https://developer.mozilla.org/fr/docs/Web/HTTP/Status#r%C3%A9ponses_derreur_c%C3%B4t%C3%A9_client

2023-12-15 15:17 UTC, moroine commented on server/src/security/accessTokenService.ts
> +    if (!user) throw Boom.forbidden("User does not exist")
==> 401 https://developer.mozilla.org/fr/docs/Web/HTTP/Status#r%C3%A9ponses_derreur_c%C3%B4t%C3%A9_client

2023-12-15 15:17 UTC, moroine commented on server/src/security/authorisationService.ts
> +      }
Dans `error` il y a possiblement d'autre choses. C'est la sécurité il faut etre strict:
```suggestion
      if (userState.error) {
        if (userState.reason !== 'VALIDATION') throw Boom.internal('Unexpected'); 
        return PendingRecruiterRole
      } else {
        return RecruiterRole
      }
```

2023-12-15 15:17 UTC, moroine commented on server/src/security/authorisationService.ts
> +      }
En gros l'idée, c'est si ça évolue dans le future comment je force le future dev à venir regarder par ici

2023-12-15 15:17 UTC, moroine commented on server/src/services/login.service.ts
> +      throw Boom.badRequest("L'état utilisateur est inconnu")
C'est pas une badRequest --> C'est un probleme de notre coté, on veut l'avoir dans Sentry et le fix --> internal

2023-12-15 15:17 UTC, moroine commented on server/src/services/userRecruteur.service.ts
>    }
Wow, on sort pour prendre le dernier ^^.

2023-12-15 15:17 UTC, moroine commented on server/tests/unit/security/accessTokenService.test.ts
>    })
Manque le test unitaire pour ce que tu viens d'ajouter comme feature (avec des UserIdentity)

2023-12-15 15:17 UTC, moroine commented on server/tests/unit/security/authorisationService.test.ts
> +        establishment_id: "#O2#E1#R1P",
`establishment_id` pas bon, on veut prendre le meme que l'entreprise deja existante

2023-12-15 17:05 UTC, kevbarns commented on server/src/http/middlewares/errorMiddleware.ts
> +      stopSession(_request, reply)
yes il peut être async https://fastify.dev/docs/latest/Reference/Server/#seterrorhandler

2023-12-15 17:09 UTC, kevbarns commented on server/src/http/routes/auth/login.controller.ts
> +        throw Boom.notFound()
C'est bien un notFound ici pour moi, 404, car l'utilisateur n'a pas été trouvé

2023-12-15 17:12 UTC, kevbarns commented on server/src/security/accessTokenService.ts
> +    if (!user) throw Boom.forbidden("User does not exist")
Pareil, utilisateur non trouvé --> notFound pour moi, pas forbidden ou unauthorized

2023-12-15 17:14 UTC, kevbarns commented on server/src/security/authorisationService.ts
> +      }
ok j'ajoute

2023-12-15 17:14 UTC, kevbarns commented on server/src/services/userRecruteur.service.ts
>    }
On sort par date pour être certain d'avoir le dernier état. Entre les scripts et le front, c'est préférable.

2023-12-15 17:20 UTC, kevbarns commented on server/tests/unit/security/authorisationService.test.ts
> +        establishment_id: "#O2#E1#R1P",
j'ai bien créé un userRecruteur & un recruiter avec un `establishment_id` identique pourtant

2023-12-18 08:42 UTC, remy-auricoste commented on server/src/services/login.service.ts
> +      throw Boom.badRequest("L'état utilisateur est inconnu")
```suggestion
      assertUnreachable(currentState)
```

2023-12-18 08:45 UTC, remy-auricoste commented on shared/security/permissions.ts
> +  permissions: ["recruiter:add_job"],
Je suis pas sûr qu'une entreprise en erreur puisse ajouter des jobs et qu'ils soient activés lorsque l'entreprise est activée

2023-12-18 08:54 UTC, moroine commented on server/src/services/userRecruteur.service.ts
>    }
Je voulais juste dire que c'est pas très opti ^^ Apres vu la taille du tableau osef

2023-12-18 08:55 UTC, moroine commented on server/tests/unit/security/authorisationService.test.ts
> +        establishment_id: "#O2#E1#R1P",
Ah yes j'avais mal vu

2023-12-18 10:46 UTC, kevbarns commented on server/src/services/login.service.ts
> +      throw Boom.badRequest("L'état utilisateur est inconnu")
j'avais mis ça à la base mais j'ai l'erreur suivante 

<img width="760" alt="Capture d’écran 2023-12-18 à 11 45 57" src="https://github.com/mission-apprentissage/labonnealternance/assets/22106329/2b652aea-883d-4f28-ac10-36aa45976a2b">

2023-12-18 10:48 UTC, kevbarns commented on shared/security/permissions.ts
> +  permissions: ["recruiter:add_job"],
Vu que l'utilisateur est authentifié, il faut ajouter un role qui lui permet d'ajouter une offre

2023-12-19 08:04 UTC, moroine requested changes

2023-12-19 08:04 UTC, moroine commented on server/tests/unit/security/accessTokenService.test.ts
> +  // useMongo --> create user pour chaque statut et tester le token et expect les differents cas.
à supprimer

2023-12-19 08:04 UTC, moroine commented on server/tests/unit/security/accessTokenService.test.ts
> +    describe("ACTIVE user", () => {
Est-ce que tu ne peux pas utiliser `describe.each` pour `cfa`, `lbaCompany` & `Active User` ?

```ts
describe.each([
   ['ACTIVE user', userACTIVE],
   ['CFA', userCFA],
   ['LBA COMPANY user', userLbaCompany],
])('%s', (_name, identity) => {
```

2023-12-19 08:04 UTC, moroine commented on server/tests/unit/security/accessTokenService.test.ts
> +    describe("ERROR user", () => {
Same ici, on peut utiliser `describe.each`

2023-12-19 21:37 UTC, GenericUser123 commented
POC comment :wink:

2023-12-20 10:52 UTC, kevbarns commented
🚀

2023-12-20 15:28 UTC, kevbarns commented
🚀

2023-12-20 19:07 UTC, moroine commented on server/tests/unit/security/accessTokenService.test.ts
> +describe.skip("accessTokenService", () => {
On est d'accord que `skip` devra etre supprimé avant de merge?

2023-12-22 10:06 UTC, kevbarns commented
🚀

2023-12-22 11:20 UTC, kevbarns commented
🚀

2023-12-22 16:16 UTC, kevbarns commented
Validé - pourra être mergé à la rentrée

2024-01-02 08:47 UTC, remy-auricoste commented on server/src/security/accessTokenService.ts
> +      throw Boom.forbidden("Not Authorized")
```suggestion
      throw Boom.forbidden()
```
Le "Not authorized" prête à confusion avec une 401.

2024-01-02 14:50 UTC, merged