fix: modification de l'action cypress pour lire les variables du vault
mission-apprentissage/labonnealternance pull request #947
Opened 2023-12-20 16:58 UTC by remy-auricoste

2023-12-20 17:23 UTC, kevbarns approved these changes

2023-12-20 19:09 UTC, moroine requested changes, later dismissed

2023-12-20 19:09 UTC, moroine commented on .github/workflows/cypress.yml
> +        run: ansible-vault view ./.infra/vault/vault.yml|yq -o=shell '.vault'|grep -E "^CYPRESS_" >> $GITHUB_ENV
Que se passe-t-il si `yq` error (probleme de format par exemple) y'a un risque d'afficher tout ou partie du vault. Le plus safe serait de faire un script et de redirect stderr vers /dev/null ou pareil que le systeme d'encrypt des logs

2023-12-21 09:49 UTC, remy-auricoste commented on .github/workflows/cypress.yml
> +        run: ansible-vault view ./.infra/vault/vault.yml|yq -o=shell '.vault'|grep -E "^CYPRESS_" >> $GITHUB_ENV
J'ai déplacé les commandes dans un script

2023-12-21 10:42 UTC, moroine approved these changes

2023-12-21 10:47 UTC, merged