feat: LBAC-1703 recherche geonear mongo au lieu d'es
mission-apprentissage/labonnealternance pull request #982
Opened 2024-01-09 20:46 UTC by alanlr

2024-01-12 18:19 UTC, alanlr commented
pas encore complètement typé mais vous pouvez déjà jeter un coup d'oeil

2024-01-15 07:07 UTC, moroine commented on server/src/db/migrations/202401090000000-migrate-geo-location-to-geo-point.ts
> +  await db.collection("recruiters").createIndex({ geopoint: "2dsphere" })
Il ne manque pas tous les champs `accent_computed` ?

2024-01-15 07:07 UTC, moroine commented on server/src/db/migrations/202401090000000-migrate-geo-location-to-geo-point.ts
> +  await db.collection("recruiters").createIndex({ geopoint: "2dsphere" })
Si tu comptes les run via les commandes, peut-etre mieux de faire un `addJob` en `queued` ici ?

2024-01-15 07:07 UTC, moroine commented on server/src/jobs/domainesMetiers/updateDomainesMetiers.ts
> +          mots_clefs_specifiques_sans_accent_computed: removeAccents([...new Set(motsClefsSpecifiques)].join(", ")),
Tu veux pas en faire une fonction `removeAccents([...new Set(motsClefsSpecifiques)].join(", "))`

2024-01-15 07:07 UTC, moroine commented on server/src/jobs/formationsCatalogue/formationsCatalogue.ts
> +// import { rebuildIndex, resetIndexAndDb } from "../../common/utils/esUtils"
A supprimer

2024-01-15 07:07 UTC, moroine commented on server/src/jobs/formationsCatalogue/formationsCatalogue.ts
> +    //await resetIndexAndDb("formationcatalogues", FormationCatalogue, { requireAsciiFolding: true })
A supprimer

2024-01-15 07:07 UTC, moroine commented on server/src/jobs/formationsCatalogue/formationsCatalogue.ts
> +    //await rebuildIndex(FormationCatalogue)
A supprimer

2024-01-15 07:07 UTC, moroine commented on server/src/services/catalogue.service.ts
> +  const formationsFromDb = await FormationCatalogue.find(query)
```suggestion
const result = await FormationCatalogue.aggregate([
 { $match: query },
 { $project: { rome_codes: 1, _id: 0 },
 { $unwind: 'rome_codes' },
 { $group: { _id: 'rome_codes' } },
]).toArray();
```

2024-01-15 07:07 UTC, moroine commented on server/src/services/catalogue.service.ts
> +  const formationsFromDb = await FormationCatalogue.find(query)
A voir, mais ça fait moins de data à sortir de la DB.

2024-01-15 07:07 UTC, moroine commented on server/src/services/catalogue.service.ts
> +  const formationsFromDb = await FormationCatalogue.find(query)
Tout dépend de la taille de la recherche surtout quand query est `{}`

2024-01-15 07:07 UTC, moroine commented on server/src/services/formation.service.ts
> +  const tags = [now.getFullYear(), now.getFullYear() + 1, now.getFullYear() + (now.getMonth() < 8 ? -1 : 2)]
Je comprends pas trop

2024-01-15 09:23 UTC, alanlr commented on server/src/services/catalogue.service.ts
> +  const formationsFromDb = await FormationCatalogue.find(query)
attention ici on a besoin de toutes les données des formations. pas seulement des codes_romes.

2024-01-15 09:23 UTC, alanlr commented on server/src/services/formation.service.ts
> +  const tags = [now.getFullYear(), now.getFullYear() + 1, now.getFullYear() + (now.getMonth() < 8 ? -1 : 2)]
une règle métier. je vais commenter pour l'expliciter.

2024-01-15 11:21 UTC, kevbarns requested changes
Il faut également penser à supprimer les synchro des autres modèles connecté à l'ES

2024-01-15 11:21 UTC, kevbarns commented on server/src/jobs/database/obfuscateCollections.ts
> +const getFakeEmail = () => `${randomUUID()}@faux-domaine.fr`.toLowerCase()
Pas nécessaire c'est toujours lowerCase

2024-01-15 11:21 UTC, kevbarns commented on server/src/services/lbajob.service.ts
> +  clauses.push({ status: RECRUITER_STATUS.ACTIF })
Pourquoi ne pas avoir mis ça directement dans la déclaration de la constante ?

2024-01-15 11:21 UTC, kevbarns commented on server/src/services/lbajob.service.ts
> +        const [establishment_location] = x.address.match(/([0-9]{5})[ ,] ?([a-zA-Z-]*)/) ?? [""]
a supprimer, plus utiliser côté front

2024-01-15 11:21 UTC, kevbarns commented on server/src/services/lbajob.service.ts
> +        x.establishment_location = establishment_location
idem

2024-01-15 11:21 UTC, kevbarns commented on server/src/services/lbajob.service.ts
> +    const longitude = recruiter?.geopoint?.coordinates ? recruiter.geopoint.coordinates[0] : 0
```suggestion
    const latitude = recruiter.geopoint.coordinates.at(1) ?? 0
    const longitude = recruiter.geopoint.coordinates.at(0) ?? 0
```

2024-01-15 11:21 UTC, kevbarns commented on server/src/services/metiers.service.ts
> +
Mettre à disposition les données dans un fichier JS

2024-01-15 11:21 UTC, kevbarns commented on server/src/services/metiers.service.ts
> +  const metiersFromDb = await DomainesMetiers.find({ codes_romes: { $in: romes } })
Pourquoi ne pas cherche dans le cache ? et du coup directement dans le fichier ?

2024-01-15 11:51 UTC, alanlr commented on server/src/services/lbajob.service.ts
> +  clauses.push({ status: RECRUITER_STATUS.ACTIF })
en effet, done

2024-01-15 13:45 UTC, alanlr commented on server/src/services/metiers.service.ts
> +  const metiersFromDb = await DomainesMetiers.find({ codes_romes: { $in: romes } })
oui bonne idée. c'est une feature annexe. je l'ai porté en mongo avant de décider de mettre en place un cache sur la collection et je n'y ai plus pensé après

2024-01-16 11:12 UTC, alanlr commented on server/src/services/metiers.service.ts
> +
feature à voir ultérieurement du coup

2024-01-16 11:14 UTC, alanlr commented on server/src/db/migrations/202401090000000-migrate-geo-location-to-geo-point.ts
> +  await db.collection("recruiters").createIndex({ geopoint: "2dsphere" })
> Il ne manque pas tous les champs `accent_computed` ?

Non pas d'usage dans cette collection. pas de recherche texte sur ces données

2024-01-18 16:26 UTC, alanlr commented
🚀

2024-01-18 17:07 UTC, alanlr commented
🚀

2024-01-19 10:39 UTC, alanlr commented
🚀

2024-01-19 11:21 UTC, alanlr commented
🚀

2024-01-19 15:03 UTC, alanlr commented
🚀

2024-01-19 17:01 UTC, alanlr commented
🚀

2024-01-19 17:42 UTC, alanlr commented
🚀

2024-01-20 13:40 UTC, alanlr commented
🚀

2024-01-22 08:07 UTC, alanlr commented
🚀

2024-01-22 12:49 UTC, alanlr commented
🚀

2024-01-22 15:34 UTC, alanlr commented
🚀

2024-01-23 17:15 UTC, kevbarns commented
🚀

2024-01-23 18:19 UTC, kevbarns commented
🚀

2024-01-23 20:55 UTC, alanlr commented
🚀

2024-01-24 10:20 UTC, kevbarns commented
🚀

2024-01-24 10:39 UTC, kevbarns commented
🚀

2024-01-24 10:57 UTC, kevbarns commented
🚀

2024-01-25 08:09 UTC, kevbarns approved these changes
🚀 👍  Supprimer le dossier `esClient`

2024-01-25 08:09 UTC, kevbarns commented on server/src/services/lbajob.service.ts
> -        x.establishment_location = establishment_location
@remy-auricoste tu peux lui filer le bout de code que t'avais modifié ici ? je ne le retrouve pas dans les PR actives

2024-01-25 09:46 UTC, merged